import type { Question } from './types';

// A curated, SAT-style question bank with full AI-tutor explanation content.
// In production this would live in PostgreSQL behind the Admin Question Bank API.

export const QUESTION_BANK: Question[] = [
  // ---------------- ALGEBRA ----------------
  {
    id: 'alg-1',
    topic: 'algebra',
    subtopic: 'Linear equations',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If 3x + 7 = 22, what is the value of x?',
    choices: [
      { id: 'A', text: '3' },
      { id: 'B', text: '5' },
      { id: 'C', text: '7' },
      { id: 'D', text: '15' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'Subtract 7 from both sides to get 3x = 15, then divide by 3 to get x = 5.',
      fastStrategy: 'Isolate the variable in two clean moves: undo the +7, then undo the ×3.',
      simplerView: 'Think "what times 3, plus 7, gives 22?" 15 + 7 = 22, and 15 ÷ 3 = 5.',
      trapNote: 'Choice D (15) is the value of 3x before you divide — students stop one step early.',
      timeTrick: 'For one-variable linears, never expand or guess — just peel operations off in reverse order.',
      whyWrong: {
        A: 'This would solve 3x + 7 = 16, not 22.',
        C: 'No operation here produces 7; likely a guess.',
        D: '15 is 3x, the value before dividing by 3.',
      },
    },
  },
  {
    id: 'alg-2',
    topic: 'algebra',
    subtopic: 'Systems of equations',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A system of equations is given: 2x + y = 11 and x − y = 1. What is the value of x?',
    choices: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '6' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Add the equations: (2x + y) + (x − y) = 11 + 1 → 3x = 12 → x = 4.',
      fastStrategy: 'When y has opposite signs across the two equations, add them to eliminate y instantly.',
      simplerView: 'The y terms (+y and −y) cancel, leaving only x to solve for.',
      trapNote: 'Choice C (5) is what you get if you solve for y instead of x.',
      timeTrick: 'Scan for variables that already cancel before doing any substitution — it saves a full minute.',
      whyWrong: {
        A: 'Arises from an arithmetic slip when subtracting instead of adding.',
        C: 'This is the value of y, not x.',
        D: 'Does not satisfy either equation.',
      },
    },
  },
  {
    id: 'alg-3',
    topic: 'algebra',
    subtopic: 'Word problems',
    section: 'Math',
    difficulty: 'medium',
    prompt:
      'A gym charges a $25 sign-up fee plus $15 per month. Which equation gives the total cost C in dollars after m months?',
    choices: [
      { id: 'A', text: 'C = 25m + 15' },
      { id: 'B', text: 'C = 15m + 25' },
      { id: 'C', text: 'C = 40m' },
      { id: 'D', text: 'C = 15(m + 25)' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The monthly rate $15 multiplies m (the variable), and the one-time $25 fee is the constant: C = 15m + 25.',
      fastStrategy: 'Tag each number as "per-something" (slope) or "one-time" (intercept). Rate sticks to the variable.',
      simplerView: 'Slope = repeating cost, intercept = starting cost. Here slope 15, intercept 25.',
      trapNote: 'Choice A swaps the rate and fee — a classic careless flip.',
      timeTrick: 'Plug in m = 0: cost should be $25 (just the fee). Only B gives 25.',
      whyWrong: {
        A: 'Swaps which number repeats — makes the $25 the monthly rate.',
        C: 'Adds the numbers wrongly and drops the constant fee.',
        D: 'Multiplies the fee by months, charging $25 every month.',
      },
    },
  },

  // ---------------- ADVANCED MATH ----------------
  {
    id: 'adv-1',
    topic: 'advanced-math',
    subtopic: 'Quadratics',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'What are the solutions to x² − 5x + 6 = 0?',
    choices: [
      { id: 'A', text: 'x = 1 and x = 6' },
      { id: 'B', text: 'x = 2 and x = 3' },
      { id: 'C', text: 'x = −2 and x = −3' },
      { id: 'D', text: 'x = −1 and x = 6' },
    ],
    correct: 'B',
    parTimeSec: 75,
    explanation: {
      correctWhy: 'Factor into (x − 2)(x − 3) = 0, so x = 2 or x = 3. They multiply to 6 and add to 5.',
      fastStrategy: 'Find two numbers that multiply to the constant (6) and add to the middle coefficient (5).',
      simplerView: '2 × 3 = 6 and 2 + 3 = 5 — that pair is your answer with flipped signs.',
      trapNote: 'Choice C flips the signs; the constant +6 with −5x means both roots are positive.',
      timeTrick: 'For monic quadratics, factoring beats the quadratic formula almost every time.',
      whyWrong: {
        A: '1 and 6 multiply to 6 but add to 7, not 5.',
        C: 'Negative roots would require the middle term to be +5x.',
        D: '−1 and 6 multiply to −6, not +6.',
      },
    },
  },
  {
    id: 'adv-2',
    topic: 'advanced-math',
    subtopic: 'Exponential growth',
    section: 'Math',
    difficulty: 'hard',
    prompt:
      'A population of bacteria doubles every 3 hours. If it starts at 500, which expression gives the population after t hours?',
    choices: [
      { id: 'A', text: '500 · 2^(3t)' },
      { id: 'B', text: '500 · 2^(t/3)' },
      { id: 'C', text: '500 + 2t/3' },
      { id: 'D', text: '500 · 3^(t/2)' },
    ],
    correct: 'B',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Doubling means base 2. It doubles once per 3 hours, so the exponent is t/3: 500 · 2^(t/3).',
      fastStrategy: 'Base = growth factor (2 for doubling); exponent = time ÷ period.',
      simplerView: 'At t = 3, exponent is 1, giving 500 · 2 = 1000 — one doubling. Correct.',
      trapNote: 'Choice A (2^(3t)) doubles every 1/3 hour — far too fast.',
      timeTrick: 'Test t = 3 mentally: the right model gives exactly double the start.',
      whyWrong: {
        A: 'Exponent 3t doubles 3 times per hour, not once per 3 hours.',
        C: 'Linear growth — but doubling is exponential.',
        D: 'Base 3 means tripling, not doubling.',
      },
    },
  },
  {
    id: 'adv-3',
    topic: 'advanced-math',
    subtopic: 'Function evaluation',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If f(x) = 2x² − 3, what is f(4)?',
    choices: [
      { id: 'A', text: '13' },
      { id: 'B', text: '29' },
      { id: 'C', text: '32' },
      { id: 'D', text: '61' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'f(4) = 2(4²) − 3 = 2(16) − 3 = 32 − 3 = 29.',
      fastStrategy: 'Square first (order of operations), then multiply, then subtract.',
      simplerView: '4 squared is 16, doubled is 32, minus 3 is 29.',
      trapNote: 'Choice C (32) forgets to subtract 3 — finishing one step early.',
      timeTrick: 'Write the substitution with parentheses: 2(4)² so you don\'t multiply before squaring.',
      whyWrong: {
        A: 'Comes from (2·4)² interpreted wrong or 2·4+... arithmetic slip.',
        C: 'Forgot the −3.',
        D: 'Computed (2·4)² − 3 = 64 − 3, squaring after multiplying.',
      },
    },
  },

  // ---------------- PROBLEM SOLVING & DATA ----------------
  {
    id: 'psd-1',
    topic: 'problem-solving-data',
    subtopic: 'Percentages',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'A jacket originally priced at $80 is on sale for 25% off. What is the sale price?',
    choices: [
      { id: 'A', text: '$20' },
      { id: 'B', text: '$55' },
      { id: 'C', text: '$60' },
      { id: 'D', text: '$75' },
    ],
    correct: 'C',
    parTimeSec: 50,
    explanation: {
      correctWhy: '25% of 80 is 20, so the sale price is 80 − 20 = $60.',
      fastStrategy: '25% off means you pay 75%. 0.75 × 80 = 60 in one step.',
      simplerView: 'A quarter off 80 is 20 off, leaving 60.',
      trapNote: 'Choice A ($20) is the discount amount, not the price you pay.',
      timeTrick: 'Convert "X% off" to "pay (100−X)%" and multiply once — avoids the subtraction step.',
      whyWrong: {
        A: 'That is the discount, not the final price.',
        B: 'Comes from subtracting 25 instead of 25%.',
        D: 'That is 80 minus only $5 — wrong percentage.',
      },
    },
  },
  {
    id: 'psd-2',
    topic: 'problem-solving-data',
    subtopic: 'Mean / statistics',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'The average of five numbers is 12. Four of the numbers are 10, 11, 13, and 14. What is the fifth number?',
    choices: [
      { id: 'A', text: '10' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '16' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Total must be 5 × 12 = 60. The four known numbers sum to 48, so the fifth is 60 − 48 = 12.',
      fastStrategy: 'Average problems are total problems: multiply the mean by the count to get the sum.',
      simplerView: 'You need everything to add to 60; you already have 48, so add 12.',
      trapNote: 'Choice C (14) tempts students who match the largest existing value.',
      timeTrick: 'Always convert "average = m" into "sum = m × n" first; the rest is subtraction.',
      whyWrong: {
        A: 'Picks an existing value with no calculation.',
        C: 'Matches the max value, ignoring the required total.',
        D: 'Over-corrects; total would become 64.',
      },
    },
  },
  {
    id: 'psd-3',
    topic: 'problem-solving-data',
    subtopic: 'Ratios & rates',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A car travels 150 miles in 3 hours. At this rate, how far will it travel in 5 hours?',
    choices: [
      { id: 'A', text: '200 miles' },
      { id: 'B', text: '225 miles' },
      { id: 'C', text: '250 miles' },
      { id: 'D', text: '300 miles' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'Rate = 150/3 = 50 mph. In 5 hours: 50 × 5 = 250 miles.',
      fastStrategy: 'Find the unit rate first, then scale to the new time.',
      simplerView: '50 miles each hour, five hours, 250 miles.',
      trapNote: 'Choice D (300) assumes 60 mph — a rounding-up mistake.',
      timeTrick: 'Unit-rate then multiply beats setting up a proportion to cross-multiply.',
      whyWrong: {
        A: 'Uses 40 mph — miscomputed the rate.',
        B: 'Scales by 4.5 hours, not 5.',
        D: 'Assumes 60 mph instead of 50.',
      },
    },
  },

  // ---------------- GEOMETRY & TRIG ----------------
  {
    id: 'geo-1',
    topic: 'geometry-trig',
    subtopic: 'Triangles',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'In a right triangle, the two legs measure 6 and 8. What is the length of the hypotenuse?',
    choices: [
      { id: 'A', text: '10' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '48' },
    ],
    correct: 'A',
    parTimeSec: 50,
    explanation: {
      correctWhy: 'By the Pythagorean theorem, √(6² + 8²) = √(36 + 64) = √100 = 10.',
      fastStrategy: 'Recognize the 3-4-5 triangle scaled by 2 → 6-8-10. No calculation needed.',
      simplerView: '6, 8, 10 is just 3, 4, 5 doubled.',
      trapNote: 'Choice C (14) is 6 + 8 — adding the legs instead of using the theorem.',
      timeTrick: 'Memorize 3-4-5 and 5-12-13 triples to skip the square roots entirely.',
      whyWrong: {
        A: '',
        B: 'No basis; possibly averaging or guessing.',
        C: 'Adds the legs instead of applying Pythagoras.',
        D: 'That is 6 × 8, the product of the legs (twice the area).',
      },
    },
  },
  {
    id: 'geo-2',
    topic: 'geometry-trig',
    subtopic: 'Circles',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A circle has a radius of 5. What is its area? (Use A = πr².)',
    choices: [
      { id: 'A', text: '10π' },
      { id: 'B', text: '25π' },
      { id: 'C', text: '50π' },
      { id: 'D', text: '100π' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'Area = π × r² = π × 5² = 25π.',
      fastStrategy: 'Square the radius first, then attach π. Don\'t confuse area with circumference.',
      simplerView: '5 squared is 25, times π.',
      trapNote: 'Choice A (10π) is the circumference formula (2πr), not the area.',
      timeTrick: 'Area uses r²; circumference uses 2r. Lock that distinction before plugging in.',
      whyWrong: {
        A: 'That is the circumference, 2πr = 10π.',
        C: 'Used 2πr² — an invented formula.',
        D: 'Used diameter (10) squared instead of radius.',
      },
    },
  },
  {
    id: 'geo-3',
    topic: 'geometry-trig',
    subtopic: 'Trigonometry',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'In a right triangle, the angle θ has an opposite side of 3 and a hypotenuse of 5. What is sin θ?',
    choices: [
      { id: 'A', text: '3/4' },
      { id: 'B', text: '3/5' },
      { id: 'C', text: '4/5' },
      { id: 'D', text: '5/3' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'sin θ = opposite / hypotenuse = 3/5.',
      fastStrategy: 'Use SOH: Sine = Opposite over Hypotenuse. Identify those two sides only.',
      simplerView: 'Sine just compares the side across from the angle to the longest side: 3 over 5.',
      trapNote: 'Choice C (4/5) is cos θ — the adjacent side (4) over the hypotenuse.',
      timeTrick: 'Write SOH-CAH-TOA at the top of the problem and circle the two sides you need.',
      whyWrong: {
        A: 'That is tan θ = opposite/adjacent = 3/4.',
        C: 'That is cos θ = adjacent/hypotenuse.',
        D: 'Inverted the ratio (hypotenuse over opposite).',
      },
    },
  },

  // ---------------- READING COMPREHENSION ----------------
  {
    id: 'read-1',
    topic: 'reading-comprehension',
    subtopic: 'Main idea',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Marine biologist Dr. Elena Vasquez spent a decade studying coral reefs once thought to be dying. To her surprise, several reefs in warmer waters were not only surviving but thriving. Her research suggested that these corals had adapted to higher temperatures, challenging the assumption that all coral is equally vulnerable to ocean warming.',
    prompt: 'Which choice best states the main idea of the passage?',
    choices: [
      { id: 'A', text: 'All coral reefs are dying due to ocean warming.' },
      { id: 'B', text: 'Some coral may be more adaptable to warming than previously assumed.' },
      { id: 'C', text: 'Dr. Vasquez spent ten years underwater.' },
      { id: 'D', text: 'Warm water is always better for coral.' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'The passage centers on the surprising finding that certain corals adapted to warmth, challenging a prior assumption — exactly what B says.',
      fastStrategy: 'The main idea matches the sentence that states a shift or surprise; here, "challenging the assumption."',
      simplerView: 'The big takeaway: not all coral reacts the same way to heat.',
      trapNote: 'Choice D overstates the finding into "always better" — SAT traps love extreme words.',
      timeTrick: 'Predict the main idea in your own words before reading choices, then match.',
      whyWrong: {
        A: 'Directly contradicts the passage, which says some reefs thrived.',
        C: 'A true-ish detail, not the main idea.',
        D: 'Too extreme — "always" is unsupported.',
      },
    },
  },
  {
    id: 'read-2',
    topic: 'reading-comprehension',
    subtopic: 'Inference',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage:
      'When the city installed protected bike lanes downtown, merchants worried that fewer cars would mean fewer customers. Yet within a year, foot traffic rose and several shops reported their best sales in a decade. The lanes, it seemed, had brought people closer to the storefronts they once sped past.',
    prompt: 'It can reasonably be inferred from the passage that:',
    choices: [
      { id: 'A', text: 'Cars are essential to local business success.' },
      { id: 'B', text: 'The merchants’ initial fears were not borne out.' },
      { id: 'C', text: 'Bike lanes always increase sales everywhere.' },
      { id: 'D', text: 'The city should remove all car lanes.' },
    ],
    correct: 'B',
    parTimeSec: 85,
    explanation: {
      correctWhy: 'Merchants feared losing customers, but sales rose — so their fears did not come true. That is a safe inference.',
      fastStrategy: 'A good inference is one short logical step from the text — not a leap.',
      simplerView: 'They worried business would drop; it actually went up. Worry unfounded.',
      trapNote: 'Choices C and D overgeneralize ("always," "all") beyond this one city.',
      timeTrick: 'Eliminate any choice containing "always," "never," "all," or "should" unless the text demands it.',
      whyWrong: {
        A: 'The passage shows the opposite — sales rose with fewer cars.',
        C: '"Always... everywhere" is an unsupported overgeneralization.',
        D: 'A policy recommendation the passage never makes.',
      },
    },
  },

  // ---------------- VOCABULARY IN CONTEXT ----------------
  {
    id: 'vocab-1',
    topic: 'vocabulary-in-context',
    subtopic: 'Word choice',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Despite the harsh reviews, the novelist remained ______, continuing to write daily and submit her work without hesitation.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'undeterred' },
      { id: 'B', text: 'distraught' },
      { id: 'C', text: 'indifferent' },
      { id: 'D', text: 'apologetic' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'She kept writing despite harsh reviews — "undeterred" means not discouraged, which fits perfectly.',
      fastStrategy: 'Cover the blank, predict your own word from context ("not discouraged"), then match.',
      simplerView: 'The word "Despite" signals she pushed on anyway → undeterred.',
      trapNote: 'Choice C (indifferent) is close but implies she didn\'t care — yet she actively continued, showing determination.',
      timeTrick: 'Find the directional clue word ("Despite," "although," "because") — it tells you the tone of the blank.',
      whyWrong: {
        B: 'Distraught means upset — contradicts continuing to write confidently.',
        C: 'Indifferent implies not caring, but she actively persists.',
        D: 'Apologetic doesn\'t fit submitting work "without hesitation."',
      },
    },
  },
  {
    id: 'vocab-2',
    topic: 'vocabulary-in-context',
    subtopic: 'Precision',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage:
      'The committee praised the proposal for its ______ structure: every section flowed logically into the next, leaving no gaps in the argument.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'haphazard' },
      { id: 'B', text: 'coherent' },
      { id: 'C', text: 'ornate' },
      { id: 'D', text: 'tentative' },
    ],
    correct: 'B',
    parTimeSec: 65,
    explanation: {
      correctWhy: '"Every section flowed logically... no gaps" describes coherence — a clear, logically connected structure.',
      fastStrategy: 'Use the explanation after the colon; it defines the blank for you.',
      simplerView: 'Logical, gap-free flow = coherent.',
      trapNote: 'Choice C (ornate) describes decoration, not logical flow — a tempting "sophisticated" word that misses meaning.',
      timeTrick: 'A colon or dash usually restates the missing word — read past it first.',
      whyWrong: {
        A: 'Haphazard means disordered — the opposite of logical flow.',
        C: 'Ornate refers to elaborate decoration, not logic.',
        D: 'Tentative means hesitant/uncertain, not well-structured.',
      },
    },
  },

  // ---------------- GRAMMAR ----------------
  {
    id: 'gram-1',
    topic: 'grammar',
    subtopic: 'Punctuation (comma splice)',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'The experiment failed the first time ______ the team refused to give up.',
    prompt: 'Which choice completes the text so it conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: ', but' },
      { id: 'B', text: ', and however' },
      { id: 'C', text: ' but,' },
      { id: 'D', text: ', ' },
    ],
    correct: 'A',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'Two independent clauses joined need a comma + coordinating conjunction; "but" shows contrast: failed... but refused to give up.',
      fastStrategy: 'Two complete sentences? Use comma + FANBOYS (for, and, nor, but, or, yet, so).',
      simplerView: 'Both halves can stand alone, so glue them with ", but".',
      trapNote: 'Choice D is a comma splice — a comma alone can\'t join two sentences.',
      timeTrick: 'Test each side of the blank: if both are full sentences, you need real punctuation, not just a comma.',
      whyWrong: {
        B: '"and however" doubles the connectors — redundant and ungrammatical.',
        C: 'Misplaces the comma after "but" instead of before it.',
        D: 'A lone comma creates a comma splice.',
      },
    },
  },
  {
    id: 'gram-2',
    topic: 'grammar',
    subtopic: 'Subject-verb agreement',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'The collection of rare stamps ______ displayed in the museum’s east wing.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: 'are' },
      { id: 'B', text: 'were' },
      { id: 'C', text: 'is' },
      { id: 'D', text: 'have been' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'The subject is "collection" (singular), not "stamps." A singular subject takes "is."',
      fastStrategy: 'Find the true subject by ignoring the "of ___" prepositional phrase.',
      simplerView: 'One collection → is. The stamps are just describing the collection.',
      trapNote: 'Choices A and B agree with "stamps," the trap noun closest to the verb.',
      timeTrick: 'Cross out "of rare stamps" — then the subject "collection... is" is obvious.',
      whyWrong: {
        A: 'Plural verb for a singular subject (collection).',
        B: 'Plural and past tense; subject is singular.',
        D: 'Plural verb form; also shifts tense unnecessarily.',
      },
    },
  },

  // ---------------- RHETORIC & EXPRESSION ----------------
  {
    id: 'rhet-1',
    topic: 'rhetoric-expression',
    subtopic: 'Transitions',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'The new policy reduced paperwork for most departments. ______, the legal team saw its workload increase as it reviewed every change.',
    prompt: 'Which transition best fits the blank?',
    choices: [
      { id: 'A', text: 'Similarly' },
      { id: 'B', text: 'However' },
      { id: 'C', text: 'For example' },
      { id: 'D', text: 'Therefore' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The second sentence contrasts (workload increased) with the first (paperwork reduced), so a contrast word — "However" — fits.',
      fastStrategy: 'Decide the relationship first: same direction, contrast, cause, or example. Then pick the matching word.',
      simplerView: 'One group got less work, another got more — that\'s a "however" contrast.',
      trapNote: 'Choice A (Similarly) wrongly signals the ideas agree.',
      timeTrick: 'Sort transitions into buckets — agree / contrast / cause / example — and match the relationship, not the vibe.',
      whyWrong: {
        A: 'Signals agreement, but the ideas contrast.',
        C: 'The second sentence is not an example of the first.',
        D: 'Implies cause-effect, but it\'s a contrast.',
      },
    },
  },
  {
    id: 'rhet-2',
    topic: 'rhetoric-expression',
    subtopic: 'Conciseness',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The report was ______ in its findings, repeating the same conclusion in multiple sections.',
    prompt: 'Which choice is most concise and precise?',
    choices: [
      { id: 'A', text: 'redundant and repetitive and said things twice' },
      { id: 'B', text: 'redundant' },
      { id: 'C', text: 'very much full of repetition that repeated' },
      { id: 'D', text: 'a thing that repeated repeatedly' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'A single precise word, "redundant," captures the meaning without wordiness.',
      fastStrategy: 'On the SAT, the most concise grammatically-correct option usually wins.',
      simplerView: 'Say it once, clearly: redundant.',
      trapNote: 'Choices A, C, and D are ironically redundant — they repeat the idea of repetition.',
      timeTrick: 'When choices differ mainly in length, lean toward the shortest correct one.',
      whyWrong: {
        A: 'Repeats the same idea three ways.',
        C: 'Wordy and circular ("repetition that repeated").',
        D: 'Vague ("a thing") and repetitive.',
      },
    },
  },
];

export function questionsByTopic(topic: string): Question[] {
  return QUESTION_BANK.filter((q) => q.topic === topic);
}

export function getQuestion(id: string): Question | undefined {
  return QUESTION_BANK.find((q) => q.id === id);
}
