import type { Question } from './types';

// A curated, SAT-style question bank with full AI-tutor explanation content.
// In production this would live in PostgreSQL behind the Admin Question Bank API.

export const QUESTION_BANK: Question[] = [
  // ---------------- ALGEBRA ----------------
  {
    id: 'alg-1',
    topic: 'algebra',
    subtopic: 'Linear equations',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If 3x + 7 = 22, what is the value of x?',
    choices: [
      { id: 'A', text: '3' },
      { id: 'B', text: '5' },
      { id: 'C', text: '7' },
      { id: 'D', text: '15' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'Subtract 7 from both sides to get 3x = 15, then divide by 3 to get x = 5.',
      fastStrategy: 'Isolate the variable in two clean moves: undo the +7, then undo the ×3.',
      simplerView: 'Think "what times 3, plus 7, gives 22?" 15 + 7 = 22, and 15 ÷ 3 = 5.',
      trapNote: 'Choice D (15) is the value of 3x before you divide — students stop one step early.',
      timeTrick: 'For one-variable linears, never expand or guess — just peel operations off in reverse order.',
      whyWrong: {
        A: 'This would solve 3x + 7 = 16, not 22.',
        C: 'No operation here produces 7; likely a guess.',
        D: '15 is 3x, the value before dividing by 3.',
      },
    },
  },
  {
    id: 'alg-2',
    topic: 'algebra',
    subtopic: 'Systems of equations',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A system of equations is given: 2x + y = 11 and x − y = 1. What is the value of x?',
    choices: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '6' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Add the equations: (2x + y) + (x − y) = 11 + 1 → 3x = 12 → x = 4.',
      fastStrategy: 'When y has opposite signs across the two equations, add them to eliminate y instantly.',
      simplerView: 'The y terms (+y and −y) cancel, leaving only x to solve for.',
      trapNote: 'Choice C (5) is what you get if you solve for y instead of x.',
      timeTrick: 'Scan for variables that already cancel before doing any substitution — it saves a full minute.',
      whyWrong: {
        A: 'Arises from an arithmetic slip when subtracting instead of adding.',
        C: 'This is the value of y, not x.',
        D: 'Does not satisfy either equation.',
      },
    },
  },
  {
    id: 'alg-3',
    topic: 'algebra',
    subtopic: 'Word problems',
    section: 'Math',
    difficulty: 'medium',
    prompt:
      'A gym charges a $25 sign-up fee plus $15 per month. Which equation gives the total cost C in dollars after m months?',
    choices: [
      { id: 'A', text: 'C = 25m + 15' },
      { id: 'B', text: 'C = 15m + 25' },
      { id: 'C', text: 'C = 40m' },
      { id: 'D', text: 'C = 15(m + 25)' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The monthly rate $15 multiplies m (the variable), and the one-time $25 fee is the constant: C = 15m + 25.',
      fastStrategy: 'Tag each number as "per-something" (slope) or "one-time" (intercept). Rate sticks to the variable.',
      simplerView: 'Slope = repeating cost, intercept = starting cost. Here slope 15, intercept 25.',
      trapNote: 'Choice A swaps the rate and fee — a classic careless flip.',
      timeTrick: 'Plug in m = 0: cost should be $25 (just the fee). Only B gives 25.',
      whyWrong: {
        A: 'Swaps which number repeats — makes the $25 the monthly rate.',
        C: 'Adds the numbers wrongly and drops the constant fee.',
        D: 'Multiplies the fee by months, charging $25 every month.',
      },
    },
  },

  // ---------------- ADVANCED MATH ----------------
  {
    id: 'adv-1',
    topic: 'advanced-math',
    subtopic: 'Quadratics',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'What are the solutions to x² − 5x + 6 = 0?',
    choices: [
      { id: 'A', text: 'x = 1 and x = 6' },
      { id: 'B', text: 'x = 2 and x = 3' },
      { id: 'C', text: 'x = −2 and x = −3' },
      { id: 'D', text: 'x = −1 and x = 6' },
    ],
    correct: 'B',
    parTimeSec: 75,
    explanation: {
      correctWhy: 'Factor into (x − 2)(x − 3) = 0, so x = 2 or x = 3. They multiply to 6 and add to 5.',
      fastStrategy: 'Find two numbers that multiply to the constant (6) and add to the middle coefficient (5).',
      simplerView: '2 × 3 = 6 and 2 + 3 = 5 — that pair is your answer with flipped signs.',
      trapNote: 'Choice C flips the signs; the constant +6 with −5x means both roots are positive.',
      timeTrick: 'For monic quadratics, factoring beats the quadratic formula almost every time.',
      whyWrong: {
        A: '1 and 6 multiply to 6 but add to 7, not 5.',
        C: 'Negative roots would require the middle term to be +5x.',
        D: '−1 and 6 multiply to −6, not +6.',
      },
    },
  },
  {
    id: 'adv-2',
    topic: 'advanced-math',
    subtopic: 'Exponential growth',
    section: 'Math',
    difficulty: 'hard',
    prompt:
      'A population of bacteria doubles every 3 hours. If it starts at 500, which expression gives the population after t hours?',
    choices: [
      { id: 'A', text: '500 · 2^(3t)' },
      { id: 'B', text: '500 · 2^(t/3)' },
      { id: 'C', text: '500 + 2t/3' },
      { id: 'D', text: '500 · 3^(t/2)' },
    ],
    correct: 'B',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Doubling means base 2. It doubles once per 3 hours, so the exponent is t/3: 500 · 2^(t/3).',
      fastStrategy: 'Base = growth factor (2 for doubling); exponent = time ÷ period.',
      simplerView: 'At t = 3, exponent is 1, giving 500 · 2 = 1000 — one doubling. Correct.',
      trapNote: 'Choice A (2^(3t)) doubles every 1/3 hour — far too fast.',
      timeTrick: 'Test t = 3 mentally: the right model gives exactly double the start.',
      whyWrong: {
        A: 'Exponent 3t doubles 3 times per hour, not once per 3 hours.',
        C: 'Linear growth — but doubling is exponential.',
        D: 'Base 3 means tripling, not doubling.',
      },
    },
  },
  {
    id: 'adv-3',
    topic: 'advanced-math',
    subtopic: 'Function evaluation',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If f(x) = 2x² − 3, what is f(4)?',
    choices: [
      { id: 'A', text: '13' },
      { id: 'B', text: '29' },
      { id: 'C', text: '32' },
      { id: 'D', text: '61' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'f(4) = 2(4²) − 3 = 2(16) − 3 = 32 − 3 = 29.',
      fastStrategy: 'Square first (order of operations), then multiply, then subtract.',
      simplerView: '4 squared is 16, doubled is 32, minus 3 is 29.',
      trapNote: 'Choice C (32) forgets to subtract 3 — finishing one step early.',
      timeTrick: 'Write the substitution with parentheses: 2(4)² so you don\'t multiply before squaring.',
      whyWrong: {
        A: 'Comes from (2·4)² interpreted wrong or 2·4+... arithmetic slip.',
        C: 'Forgot the −3.',
        D: 'Computed (2·4)² − 3 = 64 − 3, squaring after multiplying.',
      },
    },
  },

  // ---------------- PROBLEM SOLVING & DATA ----------------
  {
    id: 'psd-1',
    topic: 'problem-solving-data',
    subtopic: 'Percentages',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'A jacket originally priced at $80 is on sale for 25% off. What is the sale price?',
    choices: [
      { id: 'A', text: '$20' },
      { id: 'B', text: '$55' },
      { id: 'C', text: '$60' },
      { id: 'D', text: '$75' },
    ],
    correct: 'C',
    parTimeSec: 50,
    explanation: {
      correctWhy: '25% of 80 is 20, so the sale price is 80 − 20 = $60.',
      fastStrategy: '25% off means you pay 75%. 0.75 × 80 = 60 in one step.',
      simplerView: 'A quarter off 80 is 20 off, leaving 60.',
      trapNote: 'Choice A ($20) is the discount amount, not the price you pay.',
      timeTrick: 'Convert "X% off" to "pay (100−X)%" and multiply once — avoids the subtraction step.',
      whyWrong: {
        A: 'That is the discount, not the final price.',
        B: 'Comes from subtracting 25 instead of 25%.',
        D: 'That is 80 minus only $5 — wrong percentage.',
      },
    },
  },
  {
    id: 'psd-2',
    topic: 'problem-solving-data',
    subtopic: 'Mean / statistics',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'The average of five numbers is 12. Four of the numbers are 10, 11, 13, and 14. What is the fifth number?',
    choices: [
      { id: 'A', text: '10' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '16' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Total must be 5 × 12 = 60. The four known numbers sum to 48, so the fifth is 60 − 48 = 12.',
      fastStrategy: 'Average problems are total problems: multiply the mean by the count to get the sum.',
      simplerView: 'You need everything to add to 60; you already have 48, so add 12.',
      trapNote: 'Choice C (14) tempts students who match the largest existing value.',
      timeTrick: 'Always convert "average = m" into "sum = m × n" first; the rest is subtraction.',
      whyWrong: {
        A: 'Picks an existing value with no calculation.',
        C: 'Matches the max value, ignoring the required total.',
        D: 'Over-corrects; total would become 64.',
      },
    },
  },
  {
    id: 'psd-3',
    topic: 'problem-solving-data',
    subtopic: 'Ratios & rates',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A car travels 150 miles in 3 hours. At this rate, how far will it travel in 5 hours?',
    choices: [
      { id: 'A', text: '200 miles' },
      { id: 'B', text: '225 miles' },
      { id: 'C', text: '250 miles' },
      { id: 'D', text: '300 miles' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'Rate = 150/3 = 50 mph. In 5 hours: 50 × 5 = 250 miles.',
      fastStrategy: 'Find the unit rate first, then scale to the new time.',
      simplerView: '50 miles each hour, five hours, 250 miles.',
      trapNote: 'Choice D (300) assumes 60 mph — a rounding-up mistake.',
      timeTrick: 'Unit-rate then multiply beats setting up a proportion to cross-multiply.',
      whyWrong: {
        A: 'Uses 40 mph — miscomputed the rate.',
        B: 'Scales by 4.5 hours, not 5.',
        D: 'Assumes 60 mph instead of 50.',
      },
    },
  },

  // ---------------- GEOMETRY & TRIG ----------------
  {
    id: 'geo-1',
    topic: 'geometry-trig',
    subtopic: 'Triangles',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'In a right triangle, the two legs measure 6 and 8. What is the length of the hypotenuse?',
    choices: [
      { id: 'A', text: '10' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '48' },
    ],
    correct: 'A',
    parTimeSec: 50,
    explanation: {
      correctWhy: 'By the Pythagorean theorem, √(6² + 8²) = √(36 + 64) = √100 = 10.',
      fastStrategy: 'Recognize the 3-4-5 triangle scaled by 2 → 6-8-10. No calculation needed.',
      simplerView: '6, 8, 10 is just 3, 4, 5 doubled.',
      trapNote: 'Choice C (14) is 6 + 8 — adding the legs instead of using the theorem.',
      timeTrick: 'Memorize 3-4-5 and 5-12-13 triples to skip the square roots entirely.',
      whyWrong: {
        A: '',
        B: 'No basis; possibly averaging or guessing.',
        C: 'Adds the legs instead of applying Pythagoras.',
        D: 'That is 6 × 8, the product of the legs (twice the area).',
      },
    },
  },
  {
    id: 'geo-2',
    topic: 'geometry-trig',
    subtopic: 'Circles',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A circle has a radius of 5. What is its area? (Use A = πr².)',
    choices: [
      { id: 'A', text: '10π' },
      { id: 'B', text: '25π' },
      { id: 'C', text: '50π' },
      { id: 'D', text: '100π' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'Area = π × r² = π × 5² = 25π.',
      fastStrategy: 'Square the radius first, then attach π. Don\'t confuse area with circumference.',
      simplerView: '5 squared is 25, times π.',
      trapNote: 'Choice A (10π) is the circumference formula (2πr), not the area.',
      timeTrick: 'Area uses r²; circumference uses 2r. Lock that distinction before plugging in.',
      whyWrong: {
        A: 'That is the circumference, 2πr = 10π.',
        C: 'Used 2πr² — an invented formula.',
        D: 'Used diameter (10) squared instead of radius.',
      },
    },
  },
  {
    id: 'geo-3',
    topic: 'geometry-trig',
    subtopic: 'Trigonometry',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'In a right triangle, the angle θ has an opposite side of 3 and a hypotenuse of 5. What is sin θ?',
    choices: [
      { id: 'A', text: '3/4' },
      { id: 'B', text: '3/5' },
      { id: 'C', text: '4/5' },
      { id: 'D', text: '5/3' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'sin θ = opposite / hypotenuse = 3/5.',
      fastStrategy: 'Use SOH: Sine = Opposite over Hypotenuse. Identify those two sides only.',
      simplerView: 'Sine just compares the side across from the angle to the longest side: 3 over 5.',
      trapNote: 'Choice C (4/5) is cos θ — the adjacent side (4) over the hypotenuse.',
      timeTrick: 'Write SOH-CAH-TOA at the top of the problem and circle the two sides you need.',
      whyWrong: {
        A: 'That is tan θ = opposite/adjacent = 3/4.',
        C: 'That is cos θ = adjacent/hypotenuse.',
        D: 'Inverted the ratio (hypotenuse over opposite).',
      },
    },
  },

  // ---------------- READING COMPREHENSION ----------------
  {
    id: 'read-1',
    topic: 'reading-comprehension',
    subtopic: 'Main idea',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Marine biologist Dr. Elena Vasquez spent a decade studying coral reefs once thought to be dying. To her surprise, several reefs in warmer waters were not only surviving but thriving. Her research suggested that these corals had adapted to higher temperatures, challenging the assumption that all coral is equally vulnerable to ocean warming.',
    prompt: 'Which choice best states the main idea of the passage?',
    choices: [
      { id: 'A', text: 'All coral reefs are dying due to ocean warming.' },
      { id: 'B', text: 'Some coral may be more adaptable to warming than previously assumed.' },
      { id: 'C', text: 'Dr. Vasquez spent ten years underwater.' },
      { id: 'D', text: 'Warm water is always better for coral.' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'The passage centers on the surprising finding that certain corals adapted to warmth, challenging a prior assumption — exactly what B says.',
      fastStrategy: 'The main idea matches the sentence that states a shift or surprise; here, "challenging the assumption."',
      simplerView: 'The big takeaway: not all coral reacts the same way to heat.',
      trapNote: 'Choice D overstates the finding into "always better" — SAT traps love extreme words.',
      timeTrick: 'Predict the main idea in your own words before reading choices, then match.',
      whyWrong: {
        A: 'Directly contradicts the passage, which says some reefs thrived.',
        C: 'A true-ish detail, not the main idea.',
        D: 'Too extreme — "always" is unsupported.',
      },
    },
  },
  {
    id: 'read-2',
    topic: 'reading-comprehension',
    subtopic: 'Inference',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage:
      'When the city installed protected bike lanes downtown, merchants worried that fewer cars would mean fewer customers. Yet within a year, foot traffic rose and several shops reported their best sales in a decade. The lanes, it seemed, had brought people closer to the storefronts they once sped past.',
    prompt: 'It can reasonably be inferred from the passage that:',
    choices: [
      { id: 'A', text: 'Cars are essential to local business success.' },
      { id: 'B', text: 'The merchants’ initial fears were not borne out.' },
      { id: 'C', text: 'Bike lanes always increase sales everywhere.' },
      { id: 'D', text: 'The city should remove all car lanes.' },
    ],
    correct: 'B',
    parTimeSec: 85,
    explanation: {
      correctWhy: 'Merchants feared losing customers, but sales rose — so their fears did not come true. That is a safe inference.',
      fastStrategy: 'A good inference is one short logical step from the text — not a leap.',
      simplerView: 'They worried business would drop; it actually went up. Worry unfounded.',
      trapNote: 'Choices C and D overgeneralize ("always," "all") beyond this one city.',
      timeTrick: 'Eliminate any choice containing "always," "never," "all," or "should" unless the text demands it.',
      whyWrong: {
        A: 'The passage shows the opposite — sales rose with fewer cars.',
        C: '"Always... everywhere" is an unsupported overgeneralization.',
        D: 'A policy recommendation the passage never makes.',
      },
    },
  },

  // ---------------- VOCABULARY IN CONTEXT ----------------
  {
    id: 'read-3',
    topic: 'reading-comprehension',
    subtopic: 'Purpose',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Early telephone operators were almost all women, hired because companies believed their voices sounded more courteous to callers. The job demanded speed, patience, and an encyclopedic memory for connections — skills that, the author notes, were rarely credited as technical at the time.',
    prompt: 'The author mentions the operators’ skills mainly to:',
    choices: [
      { id: 'A', text: 'argue that women preferred telephone work to other jobs.' },
      { id: 'B', text: 'suggest the work was more skilled than it was recognized to be.' },
      { id: 'C', text: 'explain how telephones were physically built.' },
      { id: 'D', text: 'prove that men could not do the same job.' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'The author stresses skills "rarely credited as technical," pointing to undervalued expertise — exactly B.',
      fastStrategy: 'Purpose questions ask WHY a detail appears; tie it to the author’s point, not the literal fact.',
      simplerView: 'The skills line exists to say: this job was harder/smarter than people admitted.',
      trapNote: 'Choice D twists "almost all women" into a claim the passage never makes.',
      timeTrick: 'Reread the sentence just before the detail — it usually states the point the detail supports.',
      whyWrong: {
        A: 'Preference is never discussed.',
        C: 'The passage is about the work, not telephone hardware.',
        D: 'An overreach the text does not support.',
      },
    },
  },

  // ---------------- VOCABULARY IN CONTEXT ----------------
  {
    id: 'vocab-1',
    topic: 'vocabulary-in-context',
    subtopic: 'Word choice',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Despite the harsh reviews, the novelist remained ______, continuing to write daily and submit her work without hesitation.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'undeterred' },
      { id: 'B', text: 'distraught' },
      { id: 'C', text: 'indifferent' },
      { id: 'D', text: 'apologetic' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'She kept writing despite harsh reviews — "undeterred" means not discouraged, which fits perfectly.',
      fastStrategy: 'Cover the blank, predict your own word from context ("not discouraged"), then match.',
      simplerView: 'The word "Despite" signals she pushed on anyway → undeterred.',
      trapNote: 'Choice C (indifferent) is close but implies she didn\'t care — yet she actively continued, showing determination.',
      timeTrick: 'Find the directional clue word ("Despite," "although," "because") — it tells you the tone of the blank.',
      whyWrong: {
        B: 'Distraught means upset — contradicts continuing to write confidently.',
        C: 'Indifferent implies not caring, but she actively persists.',
        D: 'Apologetic doesn\'t fit submitting work "without hesitation."',
      },
    },
  },
  {
    id: 'vocab-2',
    topic: 'vocabulary-in-context',
    subtopic: 'Precision',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage:
      'The committee praised the proposal for its ______ structure: every section flowed logically into the next, leaving no gaps in the argument.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'haphazard' },
      { id: 'B', text: 'coherent' },
      { id: 'C', text: 'ornate' },
      { id: 'D', text: 'tentative' },
    ],
    correct: 'B',
    parTimeSec: 65,
    explanation: {
      correctWhy: '"Every section flowed logically... no gaps" describes coherence — a clear, logically connected structure.',
      fastStrategy: 'Use the explanation after the colon; it defines the blank for you.',
      simplerView: 'Logical, gap-free flow = coherent.',
      trapNote: 'Choice C (ornate) describes decoration, not logical flow — a tempting "sophisticated" word that misses meaning.',
      timeTrick: 'A colon or dash usually restates the missing word — read past it first.',
      whyWrong: {
        A: 'Haphazard means disordered — the opposite of logical flow.',
        C: 'Ornate refers to elaborate decoration, not logic.',
        D: 'Tentative means hesitant/uncertain, not well-structured.',
      },
    },
  },

  {
    id: 'vocab-3',
    topic: 'vocabulary-in-context',
    subtopic: 'Tone',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'Although the startup’s early demo was rough, investors found the founder’s vision so ______ that they funded it on the spot, convinced the polish would come later.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'compelling' },
      { id: 'B', text: 'tedious' },
      { id: 'C', text: 'ambiguous' },
      { id: 'D', text: 'derivative' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'Investors funded it "on the spot" despite a rough demo — the vision must have been compelling (persuasive, attractive).',
      fastStrategy: 'The result (instant funding) tells you the blank is strongly positive.',
      simplerView: 'They paid immediately → the idea grabbed them → compelling.',
      trapNote: 'The word "Although" sets up a contrast: rough demo BUT persuasive vision.',
      timeTrick: 'Let the consequence in the sentence fix the blank’s charge (+ or −) before testing words.',
      whyWrong: {
        B: 'Tedious is negative; no one funds the tedious on the spot.',
        C: 'Ambiguous vision would not inspire immediate confidence.',
        D: 'Derivative (unoriginal) contradicts the investors’ enthusiasm.',
      },
    },
  },

  // ---------------- GRAMMAR ----------------
  {
    id: 'gram-1',
    topic: 'grammar',
    subtopic: 'Punctuation (comma splice)',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'The experiment failed the first time ______ the team refused to give up.',
    prompt: 'Which choice completes the text so it conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: ', but' },
      { id: 'B', text: ', and however' },
      { id: 'C', text: ' but,' },
      { id: 'D', text: ', ' },
    ],
    correct: 'A',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'Two independent clauses joined need a comma + coordinating conjunction; "but" shows contrast: failed... but refused to give up.',
      fastStrategy: 'Two complete sentences? Use comma + FANBOYS (for, and, nor, but, or, yet, so).',
      simplerView: 'Both halves can stand alone, so glue them with ", but".',
      trapNote: 'Choice D is a comma splice — a comma alone can\'t join two sentences.',
      timeTrick: 'Test each side of the blank: if both are full sentences, you need real punctuation, not just a comma.',
      whyWrong: {
        B: '"and however" doubles the connectors — redundant and ungrammatical.',
        C: 'Misplaces the comma after "but" instead of before it.',
        D: 'A lone comma creates a comma splice.',
      },
    },
  },
  {
    id: 'gram-2',
    topic: 'grammar',
    subtopic: 'Subject-verb agreement',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'The collection of rare stamps ______ displayed in the museum’s east wing.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: 'are' },
      { id: 'B', text: 'were' },
      { id: 'C', text: 'is' },
      { id: 'D', text: 'have been' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'The subject is "collection" (singular), not "stamps." A singular subject takes "is."',
      fastStrategy: 'Find the true subject by ignoring the "of ___" prepositional phrase.',
      simplerView: 'One collection → is. The stamps are just describing the collection.',
      trapNote: 'Choices A and B agree with "stamps," the trap noun closest to the verb.',
      timeTrick: 'Cross out "of rare stamps" — then the subject "collection... is" is obvious.',
      whyWrong: {
        A: 'Plural verb for a singular subject (collection).',
        B: 'Plural and past tense; subject is singular.',
        D: 'Plural verb form; also shifts tense unnecessarily.',
      },
    },
  },

  {
    id: 'gram-3',
    topic: 'grammar',
    subtopic: 'Pronoun-antecedent agreement',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'Each of the volunteers submitted ______ timesheet before leaving the site.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: 'their' },
      { id: 'B', text: 'they’re' },
      { id: 'C', text: 'his or her' },
      { id: 'D', text: 'there' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: '"Each" is singular, so it takes a singular pronoun — "his or her" agrees in number.',
      fastStrategy: 'Words like each, every, either, neither are singular — match them with singular pronouns.',
      simplerView: 'Each = one at a time → singular → his or her.',
      trapNote: 'Choice A ("their") is the everyday-speech trap; the SAT still tests formal singular agreement here.',
      timeTrick: 'Spot the indefinite pronoun first; "each/every" almost always signals singular.',
      whyWrong: {
        A: 'Plural pronoun for a singular antecedent ("each").',
        B: '"They’re" = "they are," a contraction, not a possessive.',
        D: '"There" indicates place, not possession.',
      },
    },
  },

  // ---------------- RHETORIC & EXPRESSION ----------------
  {
    id: 'rhet-1',
    topic: 'rhetoric-expression',
    subtopic: 'Transitions',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'The new policy reduced paperwork for most departments. ______, the legal team saw its workload increase as it reviewed every change.',
    prompt: 'Which transition best fits the blank?',
    choices: [
      { id: 'A', text: 'Similarly' },
      { id: 'B', text: 'However' },
      { id: 'C', text: 'For example' },
      { id: 'D', text: 'Therefore' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The second sentence contrasts (workload increased) with the first (paperwork reduced), so a contrast word — "However" — fits.',
      fastStrategy: 'Decide the relationship first: same direction, contrast, cause, or example. Then pick the matching word.',
      simplerView: 'One group got less work, another got more — that\'s a "however" contrast.',
      trapNote: 'Choice A (Similarly) wrongly signals the ideas agree.',
      timeTrick: 'Sort transitions into buckets — agree / contrast / cause / example — and match the relationship, not the vibe.',
      whyWrong: {
        A: 'Signals agreement, but the ideas contrast.',
        C: 'The second sentence is not an example of the first.',
        D: 'Implies cause-effect, but it\'s a contrast.',
      },
    },
  },
  {
    id: 'rhet-2',
    topic: 'rhetoric-expression',
    subtopic: 'Conciseness',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The report was ______ in its findings, repeating the same conclusion in multiple sections.',
    prompt: 'Which choice is most concise and precise?',
    choices: [
      { id: 'A', text: 'redundant and repetitive and said things twice' },
      { id: 'B', text: 'redundant' },
      { id: 'C', text: 'very much full of repetition that repeated' },
      { id: 'D', text: 'a thing that repeated repeatedly' },
    ],
    correct: 'B',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'A single precise word, "redundant," captures the meaning without wordiness.',
      fastStrategy: 'On the SAT, the most concise grammatically-correct option usually wins.',
      simplerView: 'Say it once, clearly: redundant.',
      trapNote: 'Choices A, C, and D are ironically redundant — they repeat the idea of repetition.',
      timeTrick: 'When choices differ mainly in length, lean toward the shortest correct one.',
      whyWrong: {
        A: 'Repeats the same idea three ways.',
        C: 'Wordy and circular ("repetition that repeated").',
        D: 'Vague ("a thing") and repetitive.',
      },
    },
  },
  {
    id: 'rhet-3',
    topic: 'rhetoric-expression',
    subtopic: 'Sentence combining',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage:
      'A researcher wants to combine: "The bridge was built in 1932. It is still the longest of its kind in the region."',
    prompt: 'Which choice most effectively combines the two sentences?',
    choices: [
      { id: 'A', text: 'Built in 1932, the bridge is still the longest of its kind in the region.' },
      { id: 'B', text: 'The bridge was built in 1932, and it is still the longest of its kind in the region, too.' },
      { id: 'C', text: 'The bridge, which was built in 1932, it is still the longest of its kind in the region.' },
      { id: 'D', text: 'The bridge was built in 1932; the longest of its kind in the region still.' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The introductory modifier "Built in 1932" attaches cleanly to "the bridge," giving a tight, correct combination.',
      fastStrategy: 'Prefer the option that subordinates one idea into a phrase rather than stacking clauses.',
      simplerView: 'Turn the first sentence into a short opener: "Built in 1932, the bridge is still...".',
      trapNote: 'Choice C adds a redundant "it" after the relative clause — ungrammatical.',
      timeTrick: 'Cross out options with doubled subjects ("which was... it is") or tacked-on words ("too," "still" misplaced).',
      whyWrong: {
        B: 'Grammatically OK but wordy, and "too" is redundant.',
        C: 'Doubles the subject ("which was... it is").',
        D: 'The second half is a fragment with awkward word order.',
      },
    },
  },
  // ---------------- ALGEBRA (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'alg-4',
    topic: 'algebra',
    subtopic: 'Linear equations',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If 5x − 3 = 12, what is the value of x?',
    choices: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '9' },
    ],
    correct: 'C',
    parTimeSec: 40,
    explanation: {
      correctWhy: 'Add 3 to both sides: 5x = 15, then divide by 5: x = 3.',
      fastStrategy: 'Undo addition first, then division — reverse PEMDAS.',
      simplerView: 'What times 5, minus 3, gives 12? 15 − 3 = 12, so 15/5 = 3.',
      trapNote: 'Choice D (9) comes from 12 − 3 = 9 without dividing by 5.',
      timeTrick: 'Two arithmetic steps; do not over-complicate.',
      whyWrong: { A: '5(1)−3=2, not 12.', B: '5(2)−3=7, not 12.', D: 'Forgot to divide by 5.' },
    },
  },
  {
    id: 'alg-5',
    topic: 'algebra',
    subtopic: 'Linear inequalities',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'Which value of x satisfies 2x + 1 > 7?',
    choices: [
      { id: 'A', text: 'x = 2' },
      { id: 'B', text: 'x = 3' },
      { id: 'C', text: 'x = 4' },
      { id: 'D', text: 'x = −1' },
    ],
    correct: 'C',
    parTimeSec: 40,
    explanation: {
      correctWhy: 'Solve: 2x > 6, so x > 3. Only x = 4 satisfies this.',
      fastStrategy: 'Solve the inequality like an equation, then pick the choice that fits.',
      simplerView: 'x must be strictly greater than 3; only 4 qualifies.',
      trapNote: 'x = 3 satisfies 2x + 1 = 7 but NOT the strict inequality > 7.',
      timeTrick: 'Plug each choice in to verify if in doubt.',
      whyWrong: { A: '2(2)+1=5, not >7.', B: '2(3)+1=7, equal but not greater.', D: '2(−1)+1=−1.' },
    },
  },
  {
    id: 'alg-6',
    topic: 'algebra',
    subtopic: 'Systems of equations',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'If 3x − y = 10 and x + y = 6, what is the value of y?',
    choices: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '4' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Add the equations: 4x = 16, so x = 4. Then y = 6 − 4 = 2.',
      fastStrategy: 'Adding eliminates y; solve for x first, then back-substitute.',
      simplerView: 'x = 4, plug into x + y = 6 to get y = 2.',
      trapNote: 'Choice D (4) is x, not y — careful which variable you solve for.',
      timeTrick: 'Label the variable you want and circle it before you start.',
      whyWrong: { A: 'Off-by-one arithmetic.', C: 'Does not satisfy x + y = 6 with x = 4.', D: 'That is x, not y.' },
    },
  },
  {
    id: 'alg-7',
    topic: 'algebra',
    subtopic: 'Linear equations',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'The equation kx + 6 = 3x + k has no solution. What is the value of k?',
    choices: [
      { id: 'A', text: '−3' },
      { id: 'B', text: '0' },
      { id: 'C', text: '3' },
      { id: 'D', text: '6' },
    ],
    correct: 'C',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Rearrange: (k−3)x = k−6. For no solution, coefficients must match but constants differ: k=3 gives 0x = −3, impossible.',
      fastStrategy: 'No solution means parallel lines: same slope, different intercept.',
      simplerView: 'Collect x terms: (k−3)x = k−6. If k=3, left side is 0 but right side is −3 → contradiction.',
      trapNote: 'k=6 gives 3x = 0, which has the solution x = 0, so it is not "no solution."',
      timeTrick: 'Group x terms, set coefficient = 0, then check the constant side is nonzero.',
      whyWrong: { A: 'k=−3 gives −6x = −9, which has a unique solution.', B: 'k=0 gives −3x = −6, solvable.', D: 'k=6 gives 3x = 0, solvable.' },
    },
  },
  {
    id: 'alg-8',
    topic: 'algebra',
    subtopic: 'Absolute value equations',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'How many solutions does |2x − 4| = 6 have?',
    choices: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: '2' },
      { id: 'D', text: '3' },
    ],
    correct: 'C',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'Split into 2x−4=6 (x=5) and 2x−4=−6 (x=−1). Two distinct solutions.',
      fastStrategy: 'Absolute value equations always split into two cases: positive and negative.',
      simplerView: 'Distance of 6 from 4 on a number line: 4+6=10 and 4−6=−2, giving x=5 and x=−1.',
      trapNote: 'Students who forget the negative case pick 1.',
      timeTrick: 'Write both cases immediately; then solve each as a standard equation.',
      whyWrong: { A: 'There are real solutions.', B: 'Misses the second case.', D: 'Absolute value of linear gives at most 2 solutions.' },
    },
  },
  {
    id: 'alg-9',
    topic: 'algebra',
    subtopic: 'Word problems',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'Two friends share a cab fare of $d. One pays $6 more than the other. Which expression gives the smaller share?',
    choices: [
      { id: 'A', text: '(d − 6) / 2' },
      { id: 'B', text: '(d + 6) / 2' },
      { id: 'C', text: 'd / 2 + 6' },
      { id: 'D', text: 'd − 6' },
    ],
    correct: 'A',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'Let smaller = s; larger = s+6; total: 2s+6 = d → s = (d−6)/2.',
      fastStrategy: 'Label the unknown (smaller share), write the total equation, solve.',
      simplerView: 'Together they pay d, and the gap is 6: split d−6 evenly then that is the smaller portion.',
      trapNote: 'Choice B is the larger share.',
      timeTrick: 'Test with d=20: smaller = (20−6)/2 = 7, larger = 13; sum = 20. Correct.',
      whyWrong: { B: 'That is the larger share.', C: 'Adds 6 rather than accounting for the split.', D: 'Does not divide by 2.' },
    },
  },

  // ---------------- ADVANCED MATH (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'adv-4',
    topic: 'advanced-math',
    subtopic: 'Polynomials',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'What is (x + 3)(x − 3)?',
    choices: [
      { id: 'A', text: 'x² − 9' },
      { id: 'B', text: 'x² + 9' },
      { id: 'C', text: 'x² − 6x + 9' },
      { id: 'D', text: 'x² + 6x − 9' },
    ],
    correct: 'A',
    parTimeSec: 40,
    explanation: {
      correctWhy: 'This is the difference of squares pattern: (a+b)(a−b) = a² − b². Here a=x, b=3 → x²−9.',
      fastStrategy: 'Recognize conjugate pairs immediately as difference of squares.',
      simplerView: 'FOIL: x²−3x+3x−9 = x²−9. Middle terms cancel.',
      trapNote: 'Choice C is (x−3)² — a different factoring entirely.',
      timeTrick: 'Memorize (a+b)(a−b) = a²−b² to skip FOIL.',
      whyWrong: { B: 'Signs: −3×−3=+9 is wrong here; one factor is negative.', C: 'That is (x−3)², a perfect square.', D: 'Invented middle term.' },
    },
  },
  {
    id: 'adv-5',
    topic: 'advanced-math',
    subtopic: 'Function evaluation',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'If g(x) = 3x − 1, what is g(−2)?',
    choices: [
      { id: 'A', text: '−7' },
      { id: 'B', text: '−5' },
      { id: 'C', text: '5' },
      { id: 'D', text: '7' },
    ],
    correct: 'A',
    parTimeSec: 35,
    explanation: {
      correctWhy: 'g(−2) = 3(−2) − 1 = −6 − 1 = −7.',
      fastStrategy: 'Substitute directly; track the sign of the substituted value carefully.',
      simplerView: '3 times −2 is −6, minus 1 is −7.',
      trapNote: 'Choice B (−5) comes from forgetting the −1 or mishandling the sign.',
      timeTrick: 'Write parentheses: 3(−2) to avoid sign errors.',
      whyWrong: { B: '3(−2)= −6, not −4; or missed the −1.', C: 'Dropped the negative.', D: 'Used +2 instead of −2.' },
    },
  },
  {
    id: 'adv-6',
    topic: 'advanced-math',
    subtopic: 'Quadratics',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'Which is a factor of x² + 7x + 12?',
    choices: [
      { id: 'A', text: '(x + 2)' },
      { id: 'B', text: '(x + 3)' },
      { id: 'C', text: '(x − 4)' },
      { id: 'D', text: '(x − 6)' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'Find two numbers that multiply to 12 and add to 7: 3 and 4. So (x+3)(x+4).',
      fastStrategy: 'Factor by finding the pair summing to 7 with product 12.',
      simplerView: '3 × 4 = 12 and 3 + 4 = 7, so (x+3) is a factor.',
      trapNote: 'Choice A uses 2, which pairs with 6 (sum 8), not 7.',
      timeTrick: 'List factor pairs of 12: (1,12),(2,6),(3,4) — look for sum = 7.',
      whyWrong: { A: '(x+2)(x+6) gives x²+8x+12, not +7x.', C: 'Negative factor doesn\'t work with positive terms.', D: 'Same issue — negative factor.' },
    },
  },
  {
    id: 'adv-7',
    topic: 'advanced-math',
    subtopic: 'Rational expressions',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'What is the domain restriction for f(x) = (x + 2) / (x² − 4)?',
    choices: [
      { id: 'A', text: 'x ≠ 2 only' },
      { id: 'B', text: 'x ≠ −2 only' },
      { id: 'C', text: 'x ≠ 2 and x ≠ −2' },
      { id: 'D', text: 'No restriction' },
    ],
    correct: 'A',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Factor denominator: (x−2)(x+2). Cancel common (x+2) factor, leaving 1/(x−2). Restriction: x ≠ 2.',
      fastStrategy: 'Simplify the rational expression first, then state the restrictions from the simplified form (and original).',
      simplerView: 'x+2 cancels from top and bottom. Only x=2 makes denominator zero after cancellation.',
      trapNote: 'x=−2 makes the original denominator zero but is a removable discontinuity — in domain problems for simplified functions, often only non-cancellable zeros are required.',
      timeTrick: 'Factor first, cancel, then find zeros of the remaining denominator.',
      whyWrong: { B: 'x=−2 was cancelled out.', C: 'Over-restricts after cancellation.', D: 'x=2 is still excluded.' },
    },
  },
  {
    id: 'adv-8',
    topic: 'advanced-math',
    subtopic: 'Exponential growth',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'An investment grows by 10% each year. If the initial amount is $P, which expression gives the value after n years?',
    choices: [
      { id: 'A', text: 'P + 0.10n' },
      { id: 'B', text: 'P · (1.10)^n' },
      { id: 'C', text: 'P · (0.10)^n' },
      { id: 'D', text: '1.10P + n' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'Compound growth: multiply by (1 + rate) each year → P · 1.10^n.',
      fastStrategy: 'Compound growth = initial × (1 + r)^t. Match to answer.',
      simplerView: 'Each year the value is ×1.10: after n years, ×1.10 done n times.',
      trapNote: 'Choice A is simple interest (linear), not compound (exponential).',
      timeTrick: 'Check at n=1: should give 1.10P. Only B does.',
      whyWrong: { A: 'Linear, not exponential.', C: '0.10 as base means the value shrinks rapidly.', D: 'Incorrect mixing of multiplication and addition.' },
    },
  },
  {
    id: 'adv-9',
    topic: 'advanced-math',
    subtopic: 'Systems of nonlinear equations',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'How many solutions does the system y = x² and y = 2x have?',
    choices: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: '2' },
      { id: 'D', text: '3' },
    ],
    correct: 'C',
    parTimeSec: 75,
    explanation: {
      correctWhy: 'Set equal: x² = 2x → x² − 2x = 0 → x(x−2) = 0 → x = 0 or x = 2. Two solutions.',
      fastStrategy: 'Substitute the linear into the quadratic, factor, count roots.',
      simplerView: 'Two intersections: at (0,0) and (2,4).',
      trapNote: 'Students who don\'t factor correctly might find only one solution.',
      timeTrick: 'A parabola and a line through the vertex can intersect 0, 1, or 2 times — here it\'s 2.',
      whyWrong: { A: 'They do intersect.', B: 'Only if tangent; here two crossings.', D: 'Max intersections for degree-2 with line is 2.' },
    },
  },

  // ---------------- PROBLEM SOLVING & DATA (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'psd-4',
    topic: 'problem-solving-data',
    subtopic: 'Percentages',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'What is 30% of 150?',
    choices: [
      { id: 'A', text: '30' },
      { id: 'B', text: '45' },
      { id: 'C', text: '50' },
      { id: 'D', text: '60' },
    ],
    correct: 'B',
    parTimeSec: 35,
    explanation: {
      correctWhy: '0.30 × 150 = 45.',
      fastStrategy: '10% of 150 = 15; three tens = 45.',
      simplerView: '30% = 3 × 10%. 10% of 150 = 15, so 3 × 15 = 45.',
      trapNote: 'Choice C (50) is 1/3 of 150, not 30%.',
      timeTrick: 'Find 10%, then multiply for multiples of 10%.',
      whyWrong: { A: 'That is just the percent number, not applied to 150.', C: 'That is 33%, not 30%.', D: '40% of 150 = 60.' },
    },
  },
  {
    id: 'psd-5',
    topic: 'problem-solving-data',
    subtopic: 'Probability',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'A bag contains 3 red, 2 blue, and 5 green marbles. What is the probability of picking a blue marble?',
    choices: [
      { id: 'A', text: '1/5' },
      { id: 'B', text: '2/5' },
      { id: 'C', text: '1/3' },
      { id: 'D', text: '1/2' },
    ],
    correct: 'A',
    parTimeSec: 45,
    explanation: {
      correctWhy: 'Total = 10. P(blue) = 2/10 = 1/5.',
      fastStrategy: 'Favorable / Total.',
      simplerView: '2 blues out of 10 total = 2/10 = 1/5.',
      trapNote: 'Choice B (2/5) uses only the non-green count in the denominator.',
      timeTrick: 'Always find the total first; do not forget any category.',
      whyWrong: { B: 'Denominator should be 10, not 5.', C: 'Incorrect denominator.', D: 'There are not 4 blue out of 8.' },
    },
  },
  {
    id: 'psd-6',
    topic: 'problem-solving-data',
    subtopic: 'Scatter plots',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'A scatter plot shows a strong positive correlation between hours studied and test score. Which conclusion is most appropriate?',
    choices: [
      { id: 'A', text: 'Studying more causes higher test scores.' },
      { id: 'B', text: 'As hours studied increase, test scores tend to increase.' },
      { id: 'C', text: 'Students who study more always score 100%.' },
      { id: 'D', text: 'Test scores depend only on hours studied.' },
    ],
    correct: 'B',
    parTimeSec: 65,
    explanation: {
      correctWhy: 'Correlation tells us about trends, not causation. B states the trend without implying cause.',
      fastStrategy: 'Correlation ≠ causation. Avoid "causes," "always," or "only."',
      simplerView: 'Positive correlation = as one goes up, the other tends to go up.',
      trapNote: 'Choice A states causation, which correlation cannot confirm.',
      timeTrick: 'Eliminate options with "always," "causes," or "only" in correlation questions.',
      whyWrong: { A: 'Correlation doesn\'t prove causation.', C: '"Always" overgeneralizes.', D: '"Only" ignores other possible factors.' },
    },
  },
  {
    id: 'psd-7',
    topic: 'problem-solving-data',
    subtopic: 'Mean / statistics',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'A dataset has a mean of 20 and a standard deviation of 4. Which score is exactly 1.5 standard deviations above the mean?',
    choices: [
      { id: 'A', text: '22' },
      { id: 'B', text: '24' },
      { id: 'C', text: '26' },
      { id: 'D', text: '28' },
    ],
    correct: 'C',
    parTimeSec: 70,
    explanation: {
      correctWhy: '20 + 1.5 × 4 = 20 + 6 = 26.',
      fastStrategy: 'Score = mean + (z)(SD).',
      simplerView: '1.5 standard deviations = 1.5 × 4 = 6 above the mean of 20.',
      trapNote: 'Choice B (24) is only 1 standard deviation above.',
      timeTrick: 'Write out mean + n×SD mechanically.',
      whyWrong: { A: 'Only 0.5 SD above.', B: '1 SD above (20+4=24).', D: '2 SDs above (20+8=28).' },
    },
  },
  {
    id: 'psd-8',
    topic: 'problem-solving-data',
    subtopic: 'Ratios & rates',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'A factory produces widgets at a rate of 240 per hour. A defect rate of 5% is found. How many non-defective widgets are produced in an 8-hour shift?',
    choices: [
      { id: 'A', text: '1,728' },
      { id: 'B', text: '1,824' },
      { id: 'C', text: '1,920' },
      { id: 'D', text: '2,016' },
    ],
    correct: 'B',
    parTimeSec: 85,
    explanation: {
      correctWhy: 'Total = 240 × 8 = 1920. Non-defective = 95% of 1920 = 0.95 × 1920 = 1824.',
      fastStrategy: 'Find total, multiply by (1 − defect rate).',
      simplerView: '1920 widgets made; 5% are bad, so 95% = 1824 are good.',
      trapNote: 'Choice C is the total before applying the defect rate.',
      timeTrick: 'Multiply by (1 − rate) to get the "good" fraction in one step.',
      whyWrong: { A: 'Incorrect percentage applied.', C: 'That is the total before defect filter.', D: 'Added instead of subtracted defects.' },
    },
  },
  {
    id: 'psd-9',
    topic: 'problem-solving-data',
    subtopic: 'Percentages',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'A stock drops 20% then rises 25%. What is the net percentage change from the original price?',
    choices: [
      { id: 'A', text: '+5%' },
      { id: 'B', text: '0%' },
      { id: 'C', text: '+1%' },
      { id: 'D', text: '−5%' },
    ],
    correct: 'B',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Start at 100. After −20%: 80. After +25%: 80 × 1.25 = 100. Net change = 0%.',
      fastStrategy: 'Multiply the two factors: 0.80 × 1.25 = 1.00 → net zero.',
      simplerView: '80 × 1.25 = 100. Started at 100, ended at 100. No change.',
      trapNote: 'Students add/subtract the percents (−20+25=+5) rather than applying them sequentially.',
      timeTrick: 'Always compute sequential percent changes as multiplied decimals.',
      whyWrong: { A: 'Adding the percents arithmetically gives +5% but that ignores the compounding.', C: 'Incorrect.', D: 'Would apply if rose only 20% after the 20% drop.' },
    },
  },
  {
    id: 'psd-9-fix',
    topic: 'problem-solving-data',
    subtopic: 'Percentages',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'A price rises 20% and then falls 20%. What is the net percentage change?',
    choices: [
      { id: 'A', text: '0%' },
      { id: 'B', text: '−4%' },
      { id: 'C', text: '+4%' },
      { id: 'D', text: '+40%' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'Start: 100 → ×1.20 = 120 → ×0.80 = 96. Net change = −4%.',
      fastStrategy: 'Multiply factors: 1.20 × 0.80 = 0.96, so −4%.',
      simplerView: '20% up then 20% down is NOT zero because the base changes.',
      trapNote: 'Choice A (0%) is the classic trap — adding +20 and −20.',
      timeTrick: 'Use a concrete start of 100 to see the real outcome.',
      whyWrong: { A: 'The percents don\'t cancel because the base changes.', C: 'Wrong sign.', D: 'Simply adds 20+20=40.' },
    },
  },

  // ---------------- GEOMETRY & TRIG (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'geo-4',
    topic: 'geometry-trig',
    subtopic: 'Area & perimeter',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'What is the area of a rectangle with length 9 and width 4?',
    choices: [
      { id: 'A', text: '13' },
      { id: 'B', text: '26' },
      { id: 'C', text: '36' },
      { id: 'D', text: '45' },
    ],
    correct: 'C',
    parTimeSec: 30,
    explanation: {
      correctWhy: 'Area = length × width = 9 × 4 = 36.',
      fastStrategy: 'Just multiply length and width.',
      simplerView: '9 × 4 = 36.',
      trapNote: 'Choice B (26) is the perimeter (2×9 + 2×4 = 26).',
      timeTrick: 'Area = multiply; perimeter = add all sides.',
      whyWrong: { A: 'That is 9 + 4 (adding instead of multiplying).', B: 'That is the perimeter.', D: 'Arithmetic error.' },
    },
  },
  {
    id: 'geo-5',
    topic: 'geometry-trig',
    subtopic: 'Angles',
    section: 'Math',
    difficulty: 'easy',
    prompt: 'Two angles are supplementary. One angle measures 65°. What is the other?',
    choices: [
      { id: 'A', text: '25°' },
      { id: 'B', text: '90°' },
      { id: 'C', text: '115°' },
      { id: 'D', text: '295°' },
    ],
    correct: 'C',
    parTimeSec: 35,
    explanation: {
      correctWhy: 'Supplementary angles sum to 180°: 180 − 65 = 115°.',
      fastStrategy: 'Supplementary = 180°; complementary = 90°.',
      simplerView: '180 − 65 = 115.',
      trapNote: 'Choice A (25°) is the complement (90 − 65), not the supplement.',
      timeTrick: 'Remember: Supplementary = Straight line = 180°.',
      whyWrong: { A: 'Complement, not supplement.', B: 'That would make both right angles if together equaled 180.', D: '360 − 65 = 295, not supplementary.' },
    },
  },
  {
    id: 'geo-6',
    topic: 'geometry-trig',
    subtopic: 'Volume',
    section: 'Math',
    difficulty: 'medium',
    prompt: 'What is the volume of a cylinder with radius 3 and height 10? (Use V = πr²h.)',
    choices: [
      { id: 'A', text: '30π' },
      { id: 'B', text: '60π' },
      { id: 'C', text: '90π' },
      { id: 'D', text: '120π' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'V = π(3²)(10) = π(9)(10) = 90π.',
      fastStrategy: 'Square the radius first, then multiply by height and π.',
      simplerView: '3² = 9, × 10 = 90, × π = 90π.',
      trapNote: 'Choice A (30π) uses 3 instead of 3² — forgetting to square.',
      timeTrick: 'Order: square r → multiply by h → attach π.',
      whyWrong: { A: 'Used r = 3 without squaring.', B: 'Used r = 2 or arithmetic error.', D: 'Used r = 4 or incorrect calculation.' },
    },
  },
  {
    id: 'geo-7',
    topic: 'geometry-trig',
    subtopic: 'Trigonometry',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'In a right triangle, the adjacent leg is 8 and the hypotenuse is 10. What is cos θ?',
    choices: [
      { id: 'A', text: '3/5' },
      { id: 'B', text: '4/5' },
      { id: 'C', text: '3/4' },
      { id: 'D', text: '5/4' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'cos θ = adjacent / hypotenuse = 8/10 = 4/5.',
      fastStrategy: 'CAH: Cosine = Adjacent / Hypotenuse.',
      simplerView: '8/10 simplified is 4/5.',
      trapNote: 'Choice A (3/5) is sin θ (opposite = 6, since 6-8-10 is a 3-4-5 triple scaled by 2).',
      timeTrick: 'Identify the sides relative to the angle before applying SOH-CAH-TOA.',
      whyWrong: { A: 'That is sin θ (opposite/hypotenuse = 6/10 = 3/5).', C: 'That is tan θ (opposite/adjacent).', D: 'Greater than 1 — impossible for a trig ratio in a right triangle.' },
    },
  },
  {
    id: 'geo-8',
    topic: 'geometry-trig',
    subtopic: 'Coordinate geometry',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'A circle has center (2, −3) and passes through (6, −3). What is the equation of the circle?',
    choices: [
      { id: 'A', text: '(x−2)² + (y+3)² = 4' },
      { id: 'B', text: '(x+2)² + (y−3)² = 16' },
      { id: 'C', text: '(x−2)² + (y+3)² = 16' },
      { id: 'D', text: '(x−2)² + (y−3)² = 16' },
    ],
    correct: 'C',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Radius = distance from center (2,−3) to (6,−3) = 4. Equation: (x−2)²+(y+3)²=16.',
      fastStrategy: 'Find r by distance formula, then write (x−h)²+(y−k)²=r².',
      simplerView: 'They share the same y, so r = |6−2| = 4. Then r² = 16.',
      trapNote: 'Choice A has r²=4 meaning r=2, not 4.',
      timeTrick: 'Standard form: (x−h)²+(y−k)²=r² where center is (h,k).',
      whyWrong: { A: 'r² = 4 means r=2; the actual radius is 4.', B: 'Sign error in center: should be (x−2)² not (x+2)².', D: 'Sign error: (y−3)² means center y=3, but center is y=−3.' },
    },
  },
  {
    id: 'geo-9',
    topic: 'geometry-trig',
    subtopic: 'Similar triangles',
    section: 'Math',
    difficulty: 'hard',
    prompt: 'Two similar triangles have sides in a ratio of 3:5. If the area of the smaller triangle is 27, what is the area of the larger?',
    choices: [
      { id: 'A', text: '45' },
      { id: 'B', text: '63' },
      { id: 'C', text: '75' },
      { id: 'D', text: '135' },
    ],
    correct: 'C',
    parTimeSec: 90,
    explanation: {
      correctWhy: 'Area scales by the square of the ratio: (5/3)² × 27 = (25/9) × 27 = 75.',
      fastStrategy: 'Scale factor for areas = (linear scale factor)².',
      simplerView: 'Sides ratio 3:5 → area ratio 9:25. If small = 27, large = 27×(25/9) = 75.',
      trapNote: 'Choice A (45) uses the linear ratio (×5/3) instead of the squared ratio.',
      timeTrick: 'When similar figures, always square the linear ratio for area comparison.',
      whyWrong: { A: 'Used linear scale factor 5/3 without squaring.', B: 'Incorrect calculation.', D: 'Multiplied by 5 (the denominator) rather than ratio squared.' },
    },
  },

  // ---------------- READING COMPREHENSION (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'read-4',
    topic: 'reading-comprehension',
    subtopic: 'Main idea',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'Dogs have been domesticated for at least 15,000 years, making them one of humanity\'s oldest animal companions. Throughout history they have served as hunters, herders, and protectors.',
    prompt: 'What is the main point of the passage?',
    choices: [
      { id: 'A', text: 'Dogs are dangerous animals.' },
      { id: 'B', text: 'Dogs have a long history of partnership with humans.' },
      { id: 'C', text: 'Herding sheep requires trained dogs.' },
      { id: 'D', text: 'Dogs are better than cats.' },
    ],
    correct: 'B',
    parTimeSec: 50,
    explanation: {
      correctWhy: 'The passage says dogs are among humanity\'s oldest companions and have long served many roles — that is B.',
      fastStrategy: 'The main idea is the sentence that could serve as a one-sentence summary.',
      simplerView: 'Old partnership: 15,000 years + many roles = B.',
      trapNote: 'Choice C is a detail (one role), not the main idea.',
      timeTrick: 'Predict the main idea before reading choices.',
      whyWrong: { A: 'Not supported.', C: 'Single detail, not the main idea.', D: 'Not mentioned.' },
    },
  },
  {
    id: 'read-5',
    topic: 'reading-comprehension',
    subtopic: 'Detail',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The Great Barrier Reef, located off the coast of Australia, is the world\'s largest coral reef system. It supports an extraordinary diversity of marine life, including over 1,500 species of fish.',
    prompt: 'According to the passage, where is the Great Barrier Reef located?',
    choices: [
      { id: 'A', text: 'Off the coast of Brazil' },
      { id: 'B', text: 'In the Caribbean Sea' },
      { id: 'C', text: 'Off the coast of Australia' },
      { id: 'D', text: 'Near New Zealand' },
    ],
    correct: 'C',
    parTimeSec: 35,
    explanation: {
      correctWhy: 'The passage explicitly states "located off the coast of Australia."',
      fastStrategy: 'For detail questions, locate the relevant sentence and lift the answer directly.',
      simplerView: 'It says "off the coast of Australia" — choose C.',
      trapNote: 'The reef is often confused with Caribbean reefs; test-takers may guess A or B.',
      timeTrick: 'Detail questions have a single correct answer supported by exact text.',
      whyWrong: { A: 'Not mentioned.', B: 'Not mentioned.', D: 'Not mentioned.' },
    },
  },
  {
    id: 'read-6',
    topic: 'reading-comprehension',
    subtopic: 'Inference',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'When the library introduced a new self-checkout system, librarians found themselves freed from repetitive scanning tasks. They began spending more time advising patrons, leading to increased patron satisfaction.',
    prompt: 'What can be inferred from the passage?',
    choices: [
      { id: 'A', text: 'The library fired all its librarians.' },
      { id: 'B', text: 'Technology can free workers to focus on higher-value tasks.' },
      { id: 'C', text: 'Patrons disliked the self-checkout system.' },
      { id: 'D', text: 'Self-checkout replaced human interaction entirely.' },
    ],
    correct: 'B',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'Librarians shifted from routine tasks to patron advising — one step of inference: technology enabled higher-value work.',
      fastStrategy: 'A valid inference follows directly from the text with one logical step.',
      simplerView: 'Less scanning → more advising → more satisfaction. Tech helped workers do better work.',
      trapNote: 'Choice D overstates — the passage says librarians now advise more, not that humans are gone.',
      timeTrick: 'Pick the inference that is "just barely beyond" the text, not a leap.',
      whyWrong: { A: 'Not stated; librarians became more helpful.', C: 'Opposite — satisfaction increased.', D: '"Entirely" overstates the passage.' },
    },
  },
  {
    id: 'read-7',
    topic: 'reading-comprehension',
    subtopic: 'Purpose',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'Although renewable energy capacity has expanded rapidly, energy storage remains a critical bottleneck. Without better battery technology, excess solar power generated midday cannot be stored efficiently for evening use.',
    prompt: 'The author mentions "midday solar power" mainly to:',
    choices: [
      { id: 'A', text: 'argue that solar panels should only operate at night.' },
      { id: 'B', text: 'provide a concrete illustration of the storage bottleneck.' },
      { id: 'C', text: 'prove that renewable energy is ineffective.' },
      { id: 'D', text: 'explain how batteries are manufactured.' },
    ],
    correct: 'B',
    parTimeSec: 80,
    explanation: {
      correctWhy: 'The example of midday solar illustrates the storage bottleneck — excess supply that cannot be saved.',
      fastStrategy: 'Details in a passage usually support the main claim; identify that claim first.',
      simplerView: 'The paragraph says storage is a problem; midday solar is the "for example."',
      trapNote: 'Choice C overstates — the passage doesn\'t say renewables are ineffective.',
      timeTrick: 'Ask: what point does this detail support? Match it to the broader argument.',
      whyWrong: { A: 'Solar panels do not operate at night.', C: 'The passage sees renewables as expanding, not ineffective.', D: 'Battery manufacturing is off-topic.' },
    },
  },
  {
    id: 'read-8',
    topic: 'reading-comprehension',
    subtopic: 'Textual evidence',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'Researchers studied 500 adults over ten years. Those who slept at least seven hours per night had significantly lower rates of cardiovascular disease compared with those who slept fewer than six hours.',
    prompt: 'Which statement is best supported by the passage?',
    choices: [
      { id: 'A', text: 'Sleeping eight hours per night prevents all disease.' },
      { id: 'B', text: 'Seven or more hours of sleep is associated with lower cardiovascular risk.' },
      { id: 'C', text: 'The study shows that sleep causes cardiovascular disease.' },
      { id: 'D', text: 'Adults need exactly six hours of sleep to stay healthy.' },
    ],
    correct: 'B',
    parTimeSec: 75,
    explanation: {
      correctWhy: 'The passage states those sleeping ≥7 hours had lower cardiovascular rates — that is B, an association claim.',
      fastStrategy: 'Match evidence to statement; avoid "causes," "all," or "exactly" unless the text uses those words.',
      simplerView: 'Lower rates for ≥7 hours = association, not causation.',
      trapNote: 'Choice C flips causation — the study shows association, not that sleep causes disease.',
      timeTrick: 'Supported = directly stated or minimally inferred. Not overstated.',
      whyWrong: { A: '"All disease" and "prevents" go too far.', C: 'Reverses direction: less sleep correlates with more disease, not that sleep causes disease.', D: '"Exactly six" misreads the threshold and the conclusion.' },
    },
  },
  {
    id: 'read-9',
    topic: 'reading-comprehension',
    subtopic: 'Author\'s tone',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The administration hailed the new transit line as a triumph of urban planning. Critics, however, noted that the route bypassed three of the city\'s most underserved neighborhoods.',
    prompt: 'The author\'s perspective on the transit line can best be described as:',
    choices: [
      { id: 'A', text: 'enthusiastically supportive' },
      { id: 'B', text: 'openly hostile' },
      { id: 'C', text: 'balanced, presenting both praise and criticism' },
      { id: 'D', text: 'indifferent' },
    ],
    correct: 'C',
    parTimeSec: 70,
    explanation: {
      correctWhy: 'The passage presents the administration\'s positive view and critics\' negative view without taking sides — balanced.',
      fastStrategy: 'When a passage presents both sides without endorsing one, the tone is balanced/neutral.',
      simplerView: 'One side says good, one says bad, author shows both → C.',
      trapNote: 'Choice A is the administration\'s view, not the author\'s.',
      timeTrick: 'Look for the author\'s own evaluative words; if absent, the tone is neutral or balanced.',
      whyWrong: { A: 'The administration is enthusiastic, not the author.', B: 'No hostility from the author.', D: 'The author does engage by presenting both sides.' },
    },
  },

  // ---------------- VOCABULARY IN CONTEXT (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'vocab-4',
    topic: 'vocabulary-in-context',
    subtopic: 'Word choice',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The scientist was known for her ______ mind; she could solve complex problems in minutes that stumped her colleagues for days.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'slow' },
      { id: 'B', text: 'keen' },
      { id: 'C', text: 'distracted' },
      { id: 'D', text: 'ordinary' },
    ],
    correct: 'B',
    parTimeSec: 40,
    explanation: {
      correctWhy: '"Keen" means sharp/acute — perfect for someone who solves problems faster than peers.',
      fastStrategy: 'Context clue: "solve complex problems in minutes" → sharp, agile mind → keen.',
      simplerView: 'Quick problem-solving = sharp mind = keen.',
      trapNote: 'Choice D (ordinary) is opposite — ordinary minds don\'t outperform colleagues.',
      timeTrick: 'Cover the blank, predict your own word, then match.',
      whyWrong: { A: 'Slow contradicts fast problem-solving.', C: 'Distracted implies poor focus.', D: 'Ordinary doesn\'t explain exceptional speed.' },
    },
  },
  {
    id: 'vocab-5',
    topic: 'vocabulary-in-context',
    subtopic: 'Tone',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'After the disappointing loss, the coach\'s mood was ______; she sat silently in the locker room long after the team had left.',
    prompt: 'Which word best fits the blank?',
    choices: [
      { id: 'A', text: 'jubilant' },
      { id: 'B', text: 'somber' },
      { id: 'C', text: 'animated' },
      { id: 'D', text: 'tranquil' },
    ],
    correct: 'B',
    parTimeSec: 40,
    explanation: {
      correctWhy: '"Somber" means dark/serious in mood — fitting a loss and sitting alone silently.',
      fastStrategy: '"Disappointing loss" + silence → sad, heavy mood → somber.',
      simplerView: 'Loss + silence = gloomy, somber.',
      trapNote: 'Choice D (tranquil) means calm/peaceful, which misses the sadness.',
      timeTrick: 'Directional signal: "disappointing loss" → negative word in the blank.',
      whyWrong: { A: 'Jubilant means joyful — opposite of the context.', C: 'Animated means lively — opposite of sitting silently.', D: 'Tranquil lacks the sadness the context implies.' },
    },
  },
  {
    id: 'vocab-6',
    topic: 'vocabulary-in-context',
    subtopic: 'Precision',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'The author\'s writing style was ______: long sentences branched into sub-clauses, each modified by layers of qualifications and parenthetical asides.',
    prompt: 'Which word best completes the text?',
    choices: [
      { id: 'A', text: 'sparse' },
      { id: 'B', text: 'convoluted' },
      { id: 'C', text: 'lucid' },
      { id: 'D', text: 'succinct' },
    ],
    correct: 'B',
    parTimeSec: 55,
    explanation: {
      correctWhy: '"Convoluted" means complex, intricately twisted — exactly what layers of sub-clauses suggest.',
      fastStrategy: 'The colon after the blank introduces the definition: many sub-clauses = convoluted.',
      simplerView: 'Long, complicated sentences with many layers = convoluted.',
      trapNote: 'Choice C (lucid) means clear and easy to understand — opposite of the described style.',
      timeTrick: 'The clause after the colon defines the word; use it to pick.',
      whyWrong: { A: 'Sparse means minimal — opposite of long, layered sentences.', C: 'Lucid means clear — opposite.', D: 'Succinct means brief — opposite of long sentences.' },
    },
  },
  {
    id: 'vocab-7',
    topic: 'vocabulary-in-context',
    subtopic: 'Word choice',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The diplomat\'s remarks were deliberately ______; by saying nothing that could be pinned down, she kept all parties at the table without committing to any position.',
    prompt: 'Which choice best completes the text?',
    choices: [
      { id: 'A', text: 'categorical' },
      { id: 'B', text: 'equivocal' },
      { id: 'C', text: 'candid' },
      { id: 'D', text: 'blunt' },
    ],
    correct: 'B',
    parTimeSec: 65,
    explanation: {
      correctWhy: '"Equivocal" means deliberately ambiguous — designed to avoid a clear commitment. Fits perfectly.',
      fastStrategy: '"Nothing that could be pinned down" = ambiguous = equivocal.',
      simplerView: 'Vague on purpose to avoid commitment = equivocal.',
      trapNote: 'Choice C (candid) means open and honest — the opposite of deliberately ambiguous.',
      timeTrick: 'Predict your own word first: "vague" or "ambiguous" — then find the match.',
      whyWrong: { A: 'Categorical means clear and unambiguous.', C: 'Candid means frank/honest — opposite.', D: 'Blunt means direct — opposite.' },
    },
  },
  {
    id: 'vocab-8',
    topic: 'vocabulary-in-context',
    subtopic: 'Precision',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The historian described the new evidence as ______: it did not settle the debate but gave both sides fresh material to argue over.',
    prompt: 'Which word best completes the text?',
    choices: [
      { id: 'A', text: 'inconclusive' },
      { id: 'B', text: 'redundant' },
      { id: 'C', text: 'decisive' },
      { id: 'D', text: 'irrelevant' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: '"Inconclusive" means not settling the question — exactly what "did not settle the debate" says.',
      fastStrategy: 'The colon defines the blank: "did not settle → inconclusive."',
      simplerView: 'Did not settle the debate = inconclusive.',
      trapNote: 'Choice C (decisive) means settling the matter — direct opposite.',
      timeTrick: 'Definitions after colons or dashes lock in the answer.',
      whyWrong: { B: 'Redundant means unnecessary repetition — not relevant here.', C: 'Decisive = settling — opposite.', D: 'Irrelevant = not related — but both sides used it, so it was relevant.' },
    },
  },
  {
    id: 'vocab-9',
    topic: 'vocabulary-in-context',
    subtopic: 'Tone',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'His acceptance speech was surprisingly ______ for a man who had just won the highest honor in the field; he devoted most of it to crediting his collaborators and mentors.',
    prompt: 'Which word best completes the text?',
    choices: [
      { id: 'A', text: 'arrogant' },
      { id: 'B', text: 'self-aggrandizing' },
      { id: 'C', text: 'humble' },
      { id: 'D', text: 'verbose' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: '"Surprisingly humble" fits: one would expect boasting, but he credited others.',
      fastStrategy: '"Surprisingly" signals a contrast — expected behavior (boasting) vs. actual (crediting others).',
      simplerView: 'Award winner credits others instead of himself = humble.',
      trapNote: 'Choice A (arrogant) would NOT be surprising for a winner and contradicts crediting others.',
      timeTrick: '"Surprisingly" is the key signal word — find the unexpected trait.',
      whyWrong: { A: 'Arrogant = expecting him to brag, consistent with winning — not surprising.', B: 'Self-aggrandizing = boasting — contradicts crediting others.', D: 'Verbose = wordy — irrelevant to what the speech was about.' },
    },
  },

  // ---------------- GRAMMAR (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'gram-4',
    topic: 'grammar',
    subtopic: 'Apostrophes',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The ______ decision to cancel the event surprised everyone.',
    prompt: 'Which choice conforms to the conventions of Standard English? (The decision belongs to the committee.)',
    choices: [
      { id: 'A', text: 'committees\'' },
      { id: 'B', text: 'committee\'s' },
      { id: 'C', text: 'committees' },
      { id: 'D', text: 'committee' },
    ],
    correct: 'B',
    parTimeSec: 40,
    explanation: {
      correctWhy: '"Committee\'s" shows singular possession — one committee owns the decision.',
      fastStrategy: 'Singular possessive: add \'s to the singular noun.',
      simplerView: 'One committee, its decision: committee\'s.',
      trapNote: 'Choice A (committees\') would indicate multiple committees.',
      timeTrick: 'Identify singular vs. plural owner before adding the apostrophe.',
      whyWrong: { A: 'Plural possessive — there is only one committee.', C: 'Plural noun with no possessive.', D: 'No possessive at all.' },
    },
  },
  {
    id: 'gram-5',
    topic: 'grammar',
    subtopic: 'Verb tense',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'By the time the guests arrived, the chef ______ the meal.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: 'prepares' },
      { id: 'B', text: 'will prepare' },
      { id: 'C', text: 'had prepared' },
      { id: 'D', text: 'is preparing' },
    ],
    correct: 'C',
    parTimeSec: 50,
    explanation: {
      correctWhy: '"By the time [past event]" requires the past perfect (had + past participle).',
      fastStrategy: 'Past perfect signals an action completed before another past event.',
      simplerView: 'Meal was finished BEFORE guests arrived → past perfect → had prepared.',
      trapNote: 'Simple past ("prepared") is close but past perfect is required to show the sequence.',
      timeTrick: '"By the time" is a classic past-perfect trigger phrase.',
      whyWrong: { A: 'Present tense — wrong time frame.', B: 'Future tense — guests already arrived.', D: 'Present progressive — wrong time frame.' },
    },
  },
  {
    id: 'gram-6',
    topic: 'grammar',
    subtopic: 'Modifiers',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'Walking through the park, ______ caught my attention.',
    prompt: 'Which choice creates a grammatically correct sentence?',
    choices: [
      { id: 'A', text: 'a bird was seen' },
      { id: 'B', text: 'a colorful butterfly' },
      { id: 'C', text: 'it was noticed' },
      { id: 'D', text: 'the sound was heard' },
    ],
    correct: 'B',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'The participial phrase "Walking through the park" must be followed by the noun it modifies — the logical subject doing the walking. Only "a colorful butterfly caught my attention" works if we interpret the implied subject as "I," but for correctness, B keeps the sentence logical.',
      fastStrategy: 'An introductory participial phrase must touch the subject of the main clause.',
      simplerView: 'Who is walking? The implied "I" — so the subject after the comma must be the person walking.',
      trapNote: 'Choices A, C, D create dangling modifiers: a bird, "it," and a sound cannot walk.',
      timeTrick: 'Ask: who/what is doing the action in the phrase? That noun must follow the comma.',
      whyWrong: { A: 'A bird cannot walk through the park in this context without a person.', C: '"It" is vague and didn\'t do the walking.', D: 'A sound cannot walk.' },
    },
  },
  {
    id: 'gram-7',
    topic: 'grammar',
    subtopic: 'Semicolons',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The legislation passed the Senate; ______ it still faced opposition in the House.',
    prompt: 'Which transition correctly follows the semicolon?',
    choices: [
      { id: 'A', text: 'however,' },
      { id: 'B', text: 'and' },
      { id: 'C', text: 'because' },
      { id: 'D', text: 'so that' },
    ],
    correct: 'A',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'A semicolon can be followed by a conjunctive adverb like "however" (with a comma). Coordinating conjunctions like "and" follow commas, not semicolons.',
      fastStrategy: 'After a semicolon use a conjunctive adverb (however, therefore) NOT a coordinating conjunction (FANBOYS).',
      simplerView: 'Semicolon + however, = two-sentence contrast. Semicolon + and = wrong.',
      trapNote: '"and" is a FANBOYS conjunction and pairs with a comma, not a semicolon.',
      timeTrick: 'FANBOYS go with comma. Conjunctive adverbs go with semicolon.',
      whyWrong: { B: '"And" belongs after a comma (comma + and), not a semicolon.', C: '"Because" introduces a dependent clause; it doesn\'t follow a semicolon cleanly.', D: '"So that" introduces purpose, not a contrasting independent clause.' },
    },
  },
  {
    id: 'gram-8',
    topic: 'grammar',
    subtopic: 'Parallel structure',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The training program helped employees learn new skills, build confidence, and ______.',
    prompt: 'Which choice maintains parallel structure?',
    choices: [
      { id: 'A', text: 'their productivity increased' },
      { id: 'B', text: 'to improve productivity' },
      { id: 'C', text: 'improve productivity' },
      { id: 'D', text: 'for productivity improvement' },
    ],
    correct: 'C',
    parTimeSec: 55,
    explanation: {
      correctWhy: 'The series uses bare infinitives: "learn," "build," "improve" — all parallel verb forms.',
      fastStrategy: 'Match the grammatical form of the other items in the list.',
      simplerView: 'Learn / build / ??? — must be a plain verb: "improve".',
      trapNote: 'Choice B ("to improve") adds "to," breaking the parallel pattern.',
      timeTrick: 'Identify the form of the other list items first; replicate that form exactly.',
      whyWrong: { A: 'Full clause — breaks the verb series.', B: '"To improve" adds an infinitive marker absent from the other items.', D: 'Prepositional phrase — not parallel with verbs.' },
    },
  },
  {
    id: 'gram-9',
    topic: 'grammar',
    subtopic: 'Subject-verb agreement',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'Neither the principal nor the teachers ______ satisfied with the new testing policy.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: [
      { id: 'A', text: 'is' },
      { id: 'B', text: 'are' },
      { id: 'C', text: 'was' },
      { id: 'D', text: 'were' },
    ],
    correct: 'B',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'With "neither...nor," the verb agrees with the closer subject ("teachers" — plural), so "are."',
      fastStrategy: 'Neither/nor + either/or: agree with the noun closest to the verb.',
      simplerView: 'Teachers is plural and closer to the verb → are.',
      trapNote: 'Choice A ("is") agrees with "principal" (singular) but the rule is to use the closer noun.',
      timeTrick: 'Underline the subject closest to the verb; match to it.',
      whyWrong: { A: 'Matches "principal" (farther), not "teachers" (closer).', C: 'Past tense when present is needed.', D: 'Past plural — wrong tense.' },
    },
  },

  // ---------------- RHETORIC & EXPRESSION (easy ×2, medium ×1, hard ×3) ----------------
  {
    id: 'rhet-4',
    topic: 'rhetoric-expression',
    subtopic: 'Conciseness',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'The scientist made a discovery that was new and had never been made before.',
    prompt: 'Which revision is most concise?',
    choices: [
      { id: 'A', text: 'The scientist made an unprecedented discovery.' },
      { id: 'B', text: 'The scientist made a new, novel, original discovery.' },
      { id: 'C', text: 'The scientist discovered something for the first time ever.' },
      { id: 'D', text: 'The scientist made a discovery that was both new and original and had not been made before.' },
    ],
    correct: 'A',
    parTimeSec: 40,
    explanation: {
      correctWhy: '"Unprecedented" captures "new and never made before" in a single word.',
      fastStrategy: 'SAT rewards precision: one precise word beats three redundant ones.',
      simplerView: 'New + never done before = unprecedented (one word).',
      trapNote: 'Choices B and D pile up synonyms redundantly.',
      timeTrick: 'If choices repeat the same idea multiple ways, eliminate them.',
      whyWrong: { B: 'New, novel, original are all synonyms — redundant.', C: 'Wordy and informal.', D: 'Lists three synonyms unnecessarily.' },
    },
  },
  {
    id: 'rhet-5',
    topic: 'rhetoric-expression',
    subtopic: 'Transitions',
    section: 'Reading & Writing',
    difficulty: 'easy',
    passage: 'Exercise improves cardiovascular health. ______, it also boosts mood by releasing endorphins.',
    prompt: 'Which transition best connects these sentences?',
    choices: [
      { id: 'A', text: 'However' },
      { id: 'B', text: 'Furthermore' },
      { id: 'C', text: 'Therefore' },
      { id: 'D', text: 'In contrast' },
    ],
    correct: 'B',
    parTimeSec: 40,
    explanation: {
      correctWhy: 'Both sentences praise exercise — "Furthermore" adds another positive benefit without contrast.',
      fastStrategy: 'Both ideas agree and add up → use an additive transition (furthermore, in addition, also).',
      simplerView: 'Good for heart AND good for mood — adding info, not contrasting.',
      trapNote: 'Choice A (However) signals a contrast that does not exist here.',
      timeTrick: 'Additive ideas = furthermore/moreover/also. Contrasting ideas = however/yet/but.',
      whyWrong: { A: 'No contrast — both ideas are benefits.', C: 'Therefore implies causation, not addition.', D: 'In contrast signals opposition — none exists here.' },
    },
  },
  {
    id: 'rhet-6',
    topic: 'rhetoric-expression',
    subtopic: 'Sentence combining',
    section: 'Reading & Writing',
    difficulty: 'medium',
    passage: 'A student wants to combine: "The concert was sold out. Thousands of fans waited outside."',
    prompt: 'Which combines the sentences most effectively?',
    choices: [
      { id: 'A', text: 'The concert was sold out, and thousands of fans waited outside.' },
      { id: 'B', text: 'Sold out, the concert had thousands of fans waiting outside.' },
      { id: 'C', text: 'The concert was sold out; therefore, thousands of fans waited outside.' },
      { id: 'D', text: 'Thousands of fans waited outside because the concert was sold out.' },
    ],
    correct: 'D',
    parTimeSec: 65,
    explanation: {
      correctWhy: 'D best shows the causal relationship: fans waited BECAUSE it was sold out. It is concise and logical.',
      fastStrategy: 'Identify the relationship: cause-effect → use "because."',
      simplerView: 'Sold out caused the waiting outside → "because" connects them best.',
      trapNote: 'Choice A (comma + and) is grammatically fine but misses the causal link.',
      timeTrick: 'Ask "why did this happen?" — if there is a cause, use because/since.',
      whyWrong: { A: '"And" treats both as equal facts without showing cause.', B: 'Awkward modifier.', C: '"Therefore" implies the sold-out show resulted in fans waiting — plausible but "because" is tighter.' },
    },
  },
  {
    id: 'rhet-7',
    topic: 'rhetoric-expression',
    subtopic: 'Transitions',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'Many researchers believe that stress shortens telomeres, accelerating aging. ______, some studies have found no significant link between stress and telomere length in healthy adults.',
    prompt: 'Which transition best fits the blank?',
    choices: [
      { id: 'A', text: 'As a result' },
      { id: 'B', text: 'Similarly' },
      { id: 'C', text: 'Nevertheless' },
      { id: 'D', text: 'In addition' },
    ],
    correct: 'C',
    parTimeSec: 65,
    explanation: {
      correctWhy: '"Nevertheless" acknowledges a prevailing view and introduces a countering finding — exactly the contrast needed.',
      fastStrategy: '"Many believe X... [contrast] some find not-X" = concession transition.',
      simplerView: 'First idea: stress shortens telomeres. Second idea: some studies say no link. Contrast.',
      trapNote: '"However" would also work, but "Nevertheless" is specifically for despite-the-foregoing contrasts.',
      timeTrick: 'Concession transitions: nevertheless, nonetheless, even so, yet.',
      whyWrong: { A: '"As a result" signals cause-effect, not contrast.', B: '"Similarly" signals agreement, not contradiction.', D: '"In addition" adds a similar point — no contrast.' },
    },
  },
  {
    id: 'rhet-8',
    topic: 'rhetoric-expression',
    subtopic: 'Sentence combining',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'A student wants to combine: "The treaty was signed in 1648. It ended thirty years of devastating warfare across Europe."',
    prompt: 'Which option most effectively combines the sentences?',
    choices: [
      { id: 'A', text: 'The treaty was signed in 1648 and it ended thirty years of devastating warfare across Europe.' },
      { id: 'B', text: 'Signed in 1648, the treaty ended thirty years of devastating warfare across Europe.' },
      { id: 'C', text: 'The treaty, which in 1648 was signed, it ended thirty years of warfare.' },
      { id: 'D', text: 'In 1648, it ended thirty years of warfare and the treaty was signed.' },
    ],
    correct: 'B',
    parTimeSec: 65,
    explanation: {
      correctWhy: 'B places the date in a tight participial phrase and flows cleanly into the main action.',
      fastStrategy: 'Subordinate the less important detail (date) into a phrase; keep the key action as the main clause.',
      simplerView: '"Signed in 1648" = quick intro phrase; "the treaty ended..." = main claim.',
      trapNote: 'Choice C doubles the subject ("which... it") — ungrammatical.',
      timeTrick: 'Introductory participial phrases trim wordiness and elevate style.',
      whyWrong: { A: 'Grammatically fine but flat — "and" gives equal weight to both facts.', C: 'Redundant subject ("which... it").', D: 'Vague pronoun "it" and awkward order.' },
    },
  },
  {
    id: 'rhet-9',
    topic: 'rhetoric-expression',
    subtopic: 'Relevance',
    section: 'Reading & Writing',
    difficulty: 'hard',
    passage: 'The article discusses the impact of urban heat islands on public health. The author wants to add a sentence. Which sentence is most relevant?',
    prompt: 'Which choice best adds relevant information?',
    choices: [
      { id: 'A', text: 'Urban heat islands form when buildings and pavement absorb and re-emit heat, raising city temperatures.' },
      { id: 'B', text: 'Many cities have professional sports teams that attract tourism.' },
      { id: 'C', text: 'Public transportation is a growing area of urban investment.' },
      { id: 'D', text: 'Urban planners debate the best strategies for road maintenance.' },
    ],
    correct: 'A',
    parTimeSec: 60,
    explanation: {
      correctWhy: 'The article is about urban heat islands and health — A explains what urban heat islands are, directly relevant.',
      fastStrategy: 'Relevance = ties directly to the topic of the passage, not just to the word "urban."',
      simplerView: 'Topic: urban heat islands → explain what they are = A.',
      trapNote: 'Choices B, C, and D are about urban topics but not about heat islands or health.',
      timeTrick: 'Check: does the sentence address the specific subject (heat islands, health) or just the broad setting (city)?',
      whyWrong: { B: 'Sports teams are unrelated to heat or health.', C: 'Transportation doesn\'t address heat islands.', D: 'Road maintenance is tangential.' },
    },
  },
];

export function questionsByTopic(topic: string): Question[] {
  return QUESTION_BANK.filter((q) => q.topic === topic);
}

export function getQuestion(id: string): Question | undefined {
  return QUESTION_BANK.find((q) => q.id === id);
}
